### ISSUE TITLE
Can't install on Ubuntu 18.04

### ISSUE THREAD

**Issue by definitio** [jellyfin/jellyfin-ffmpeg#1]
```
# apt install jellyfin-ffmpeg
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 jellyfin-ffmpeg : Depends: libaom0 (>= 1.0.0) but it is not installable
                   Depends: libc6 (>= 2.28) but 2.27-3ubuntu1 is to be installed
                   Depends: libcodec2-0.8.1 but it is not installable
                   Depends: libgnutls30 (>= 3.6.5) but 3.5.18-1ubuntu1 is to be installed
                   Depends: libgsm1 (>= 1.0.18) but 1.0.13-4build1 is to be installed
                   Depends: libsndio7.0 (>= 1.1.0) but it is not installable
                   Depends: libssh-gcrypt-4 (>= 0.8.0) but 0.8.0~20170825.94fa1e38-1ubuntu0.2 is to be installed
                   Depends: libva2 (>= 2.2.0) but 2.1.0-3 is to be installed
                   Depends: libvidstab1.1 but it is not installable
                   Depends: libx264-155 but it is not installable
                   Depends: libx265-165 (>= 2.9) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by joshuaboniface** [comment]
Thanks for reporting this, it looks like I'll have to build it explicitly for Ubuntu too - which release are you on @definitio ?

In theory it shouldn't be required as long as system `ffmpeg` is <4.1, but that depends on which release.

**Comment by definitio** [comment]
@joshuaboniface, Ubuntu 18.04.2 LTS (GNU/Linux 4.15.18-11-pve x86_64).

**Comment by JustAMan** [comment]
I think it's still required for Ubuntu, they're probably still shipping`avconv` disguised as `ffmpeg`, which doesn't work for Jellyfin.

**Comment by NeverEnoughTime** [comment]
I'm running Ubuntu 18.04.2 LTS and it looks like ffmpeg 3.4.4 is installed by default. 

This is the -version output:
ffmpeg version 3.4.4-0ubuntu0.18.04.1 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
libavutil      55. 78.100 / 55. 78.100
libavcodec     57.107.100 / 57.107.100
libavformat    57. 83.100 / 57. 83.100
libavdevice    57. 10.100 / 57. 10.100
libavfilter     6.107.100 /  6.107.100
libavresample   3.  7.  0 /  3.  7.  0
libswscale      4.  8.100 /  4.  8.100
libswresample   2.  9.100 /  2.  9.100
libpostproc    54.  7.100 / 54.  7.100

I can't seems to swap that version out for jellyfin-ffmpeg or for one from another repository either.

**Comment by NeverEnoughTime** [comment]
I'm running Ubuntu 18.04.2 LTS and it looks like ffmpeg 3.4.4 is installed by default.

@joshuaboniface This is the -version output:
ffmpeg version 3.4.4-0ubuntu0.18.04.1 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
libavutil 55. 78.100 / 55. 78.100
libavcodec 57.107.100 / 57.107.100
libavformat 57. 83.100 / 57. 83.100
libavdevice 57. 10.100 / 57. 10.100
libavfilter 6.107.100 / 6.107.100
libavresample 3. 7. 0 / 3. 7. 0
libswscale 4. 8.100 / 4. 8.100
libswresample 2. 9.100 / 2. 9.100
libpostproc 54. 7.100 / 54. 7.100

I can't seems to swap that version out for jellyfin-ffmpeg or for one from another repository either.

**Comment by definitio** [comment]
Fixed
