### ISSUE TITLE
Port the jellyfin build system to jellyfin-ffmpeg to have a unified way of building the packages.

### ISSUE THREAD

**Issue by SR-Lut3t1um** [jellyfin/jellyfin-ffmpeg#148]
Right now, a lot of jellyfin project have their own build system and thus support different platforms. One example would be that jellyfin-ffmpeg is not providing rpms. By using a unified way of building the packages this could be solved an changes to support a different platform could be ported instead of needing a rewrite. 

Alternatively something like https://build.opensuse.org/ could be used.

**Comment by dkanada** [comment]
GitHub Actions is our solution of choice for providing builds, and the only reason jellyfin-ffmpeg has no RPMs is because no one has written them yet. We do have some projects on Azure at the moment but those are slowly being phased out.
