### ISSUE TITLE
No assets for latest two releases?

### ISSUE THREAD

**Issue by TwizzyDizzy** [jellyfin/jellyfin-ffmpeg#15]
Hi folks,

is there a reason that there are no assets (e.g. `.deb` packages) for the latest releases (`4.2.1-3`,`4.2.1-2`)? :)

Cheers
Thomas

**Comment by JustAMan** [comment]
Because they're hosted as part of our debian repo? https://jellyfin.org/docs/general/administration/installing.html#repository :)

P.S. All available here: https://repo.jellyfin.org/releases/server/debian/ffmpeg/

**Comment by joshuaboniface** [comment]
^^ That, but also they should be uploaded to the release too. Script fail. Should be available shortly.

**Comment by TwizzyDizzy** [comment]
Thanks! For both replies :)

Cheers
Thomas
