### ISSUE TITLE
The site of gitlab.freedesktop.org is down for a while. How to build?

### ISSUE THREAD

**Issue by crotoc** [jellyfin/jellyfin-ffmpeg#157]
**Describe The Bug**
The gitlab.freedesktop.org is down for two days. So some libraries hosted on the site can not be downloaded and installed.

**Steps To Reproduce**

./build jammy target

**Expected Behavior**
Succeeded to compile and build a deb

**System (please complete the following information):**

- **Platform:** [e.g. Linux, Windows]
- **Operating System:** [e.g. Ubuntu 20.04, Debian 11, Windows 10]
- **Virtualization**: [e.g. Docker, KVM, LXC]
- **Jellyfin Version:** [e.g. 10.7.7]
- **Jellyfin-FFmpeg Version:** [e.g. 4.4.1-2]
- **Hardware Acceleration:** [e.g. QSV, Nvidia, VAAPI, AMD AMF]
- **CPU & GPU Model**: [e.g. i7-1165G7, UHD 630, GTX 1650, VEGA 64]

**MediaInfo**

**FFmpeg Logs**

**Additional Context**

Thanks for checking this!

**Comment by crotoc** [comment]
I work around it by modifying the code to download the .xz directly from https://dri.freedesktop.org/libdrm/.

**Comment by Shadowghost** [comment]
We're keeping an eye on it. If it doesn't come up again I guess we'll need to switch to the source tars within the build scripts

**Comment by nyanmisaka** [comment]
https://www.phoronix.com/scan.php?page=news_item&px=FreeDesktop-GitLab-2022-Crash

Hopefully it will be resolved soon.

**Comment by crotoc** [comment]
It's resolved! Thanks!
