### ISSUE TITLE
FFMpeg should be built with --enable-libmfx for QuickSyncVideo

### ISSUE THREAD

**Issue by cryptobank** [jellyfin/jellyfin-ffmpeg#16]
I've been running a locally compiled ffmpeg on Debian to allow QSV on Linux. Jellyfin-ffmpeg should do the same. QSV on Linux is very usable with the iHD driver as an alternative to VAAPI.

**Comment by JustAMan** [comment]
For a note - you can see how to build MFX support from scratch here: https://github.com/JustAMan/ffmpeg-standalone-build/blob/master/Makefile.internal#L645-L705

**Comment by Artiume** [comment]
So in order to fully enable QSV, we need nonfree libs. To do this, you must build your own ffmpeg binary. To build ours with nonfree, uncomment these lines

https://github.com/jellyfin/jellyfin-ffmpeg/blob/78cf50273607b3feb494d32031c33bbc2775fad7/docker-build.sh#L57-L107

**Comment by Shadowghost** [comment]
`jellyfin-ffmpeg` now includes the required driver for QSV on Linux.
