### ISSUE TITLE
Replacing jellyfin-ffmpeg with jellyfin-ffmpeg5 causes apt to uninstall jellyfin as it is no longer required

### ISSUE THREAD

**Issue by Krupski19** [jellyfin/jellyfin-ffmpeg#164]
**Describe The Bug**
When installing jellyfin-ffmpeg5, it replaces jellyfin-ffmpeg, and causes apt to uninstall Jellyfin as it is no longer required.  Trying to install Jellyfin after installing jellyfin-ffmpeg5 results in a dependency error, stating that it depends on jellyfin-ffmeg, but it is not going to be installed.

**Steps To Reproduce**
1. Install through apt Jellyfin
2. Install through apt jellyfin-ffmpeg5
3. Jellfin will be removed as it is no longer required
4. Try to install Jellyfin after installing jellyfin-ffmpeg5, which will result in a dependency error and Jellyfin will not be installed

**Expected Behavior**
Installing jellyfin-ffmpeg5 does not break dependencies with jellyfin and does not cause it to be removed when installing jellyfin-ffmpeg5

**System (please complete the following information):**

- **Platform:** Linux
- **Operating System:** Ubuntu 20.04
- **Virtualization**: N/A
- **Jellyfin Version:** 10.8.0
- **Jellyfin-FFmpeg Version:** 5.0.1-6-focal

**Comment by nyanmisaka** [comment]
Remove unstable from `/etc/apt/sources.list.d/jellyfin.list`.

**Comment by Krupski19** [comment]
Can confirm that jellyfin is installable with jellyfin-ffmpeg5 on the stable branch, and does not work on the unstable.  Will this dependency issue with jellyfin-ffmpeg5 be resolved on the unstable branch as well?

**Comment by nyanmisaka** [comment]
Our release manager forget to push [this commit](https://github.com/jellyfin/jellyfin-metapackages/commit/1b1a148c5bafc9c49abe53a361d8b6e80d4ce12e) to the unstable repo. It belongs to jellyfin-metapackeges.

**Comment by Krupski19** [comment]
Okay, thank you so much for the help, much appreciated!
