### ISSUE TITLE
Can't install on Debian Bullseye "Depends: libx265-165 (>= 2.9) but it is not installable"

### ISSUE THREAD

**Issue by ioogithub** [jellyfin/jellyfin-ffmpeg#17]
**Describe the bug**
The package cannot be installed.

**To Reproduce**
sudo apt install jellyfin

**Expected behavior**
I expect it will install.

**Logs**

From the terminal:
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  **jellyfin : Depends: jellyfin-ffmpeg but it is not going to be installed**
> E: Unable to correct problems, you have held broken packages.

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 **jellyfin-ffmpeg : Depends: libx265-165 (>= 2.9) but it is not installable**
E: Unable to correct problems, you have held broken packages.

**System (please complete the following information):**
 - OS: Debian Bullseye

**Additional context**
I tried to install ffmpeg as a package separately however this did not work. I also tried installing from the .deb files provided and also from the repo, both end up with a broken packages and not installable errors.

**Comment by JustAMan** [comment]
As this is actually a problem with `jellyfin-ffmpeg` package I've transferred your issue to its repo.

**Comment by Artiume** [comment]
Just ran into this haha

**Comment by Artiume** [comment]
For arm32v7/debian:buster-slim

```
The following packages have unmet dependencies:
 jellyfin-ffmpeg : Depends: libx264-152 but it is not installable
                   Depends: libx265-146 (>= 2.6) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by Artiume** [comment]
Found 

https://packages.debian.org/sid/armhf/libx265-179/filelist
https://packages.debian.org/bullseye/libx265-dev

https://tracker.debian.org/pkg/x264
https://packages.debian.org/unstable/libx264-155

**Comment by joshuaboniface** [comment]
Fixing this requires explicit support for Bullseye in the `build` script, which shouldn't be too hard to add - the issue would come when packages upgrade in Bullseye and our required deps suddenly disappear. That said it's not a lot of work to support this, and I'm doing some testing now to do so.

**Comment by JustAMan** [comment]
Isn't it closed by https://github.com/jellyfin/jellyfin-ffmpeg/pull/21 ?

**Comment by Artiume** [comment]
let me test it

**Comment by Artiume** [comment]
```
The following packages have unmet dependencies:
 jellyfin-ffmpeg : Depends: libx264-152 but it is not installable
                   Depends: libx265-146 (>= 2.6) but it is not installable
E: Unable to correct problems, you have held broken packages.
```
Still got this error

**Comment by joshuaboniface** [comment]
@Artiume Release hasn't been built yet (just confirming everything works on my side), but you can self-compile from Master right now to get some testing going.

**Comment by Artiume** [comment]
That'd explain it... 

so... not sure how to do that lol

**Comment by joshuaboniface** [comment]
The integrated build script should do it (requires Docker):

```
git clone https://github.com/jellyfin/jellyfin-ffmpeg
cd jellyfin-ffmpeg
./build bullseye armhf
```

**Comment by Artiume** [comment]
can i do that within my jellyfin dockerfile or should i do it externally then pull it in? i feel like this kinda complicates my build test lol

**Comment by joshuaboniface** [comment]
Building the .deb externally on an amd64 system is best, but then the .deb can be used inside your existing Docker container.

**Comment by Artiume** [comment]
ok, i built it, but it was for amd64 lol. I need it to specify armhf right?

**Comment by joshuaboniface** [comment]
@Artiume That's right, the second argument to `build` is the architecture to build for.

**Comment by Artiume** [comment]
Was the new build released yet?

**Comment by dkanada** [comment]
Oh I thought it was.

**Comment by mitchellurgero** [comment]
I installed this deps (as a workaround for now) by doing (On ubuntu 19.10/19.04):

```bash
wget http://turul.canonical.com/ubuntu-ports/pool/universe/x/x265/libx265-165_2.9-4_arm64.deb
sudo dpkg -i libx265-165_2.9-4_arm64.deb
sudo apt install jellyfin
```

**Comment by Artiume** [comment]
It should be fixed for debian.

**Comment by ddjxie** [comment]
This still fails for me on Debian Bullseye. However, I fixed it by manually installing it:

```
wget http://ftp.br.debian.org/debian/pool/main/x/x264/libx264-159_0.159.2999+git296494a-2+b1_amd64.deb
sudo dpkg -i libx264-159_0.159.2999+git296494a-2+b1_amd64.deb
sudo apt install jellyfin
```
