### ISSUE TITLE
Force i965 driver

### ISSUE THREAD

**Issue by Caros2017** [jellyfin/jellyfin-ffmpeg#170]
**Describe The Bug**
I am using [Frigate](https://github.com/blakeblackshear/frigate). On the background Frigate uses jellyfin.

Before jellyfin-ffmpeg, Frigate uses regular ffmpeg. In ffmpeg the regular VA-API hwacl worked perfectly on the J4125 processor. It used the i965 driver on the background. Since migrating to jellyfin-ffmpeg it's not working anymore. On this processor it's impossible to get hwacl working on QSV or VA-API. The major difference is that `vainfo` shows the i965 driver on regular ffmpeg and uses the iHD driver on jellyfin-ffmpeg.

I tried a lot to force to the i965, but I cannot get this working.

**Expected Behavior**

**System (please complete the following information):**

- **Platform:** Linux
- **Operating System:** DSM7.1
- **Virtualization**: Docker
- **Jellyfin-FFmpeg Version:** multiple
- **Hardware Acceleration:** VAAPI
- **CPU & GPU Model**: J4125

**Additional Context**
This whole [bugreport ](https://github.com/blakeblackshear/frigate/issues/3227)

**Comment by nyanmisaka** [comment]
https://github.com/jellyfin/jellyfin-ffmpeg/blob/6bd84bbf7ed35d45b67c9f45ced1adcf4f873d34/docker-build.sh#L180

With our custom ffmpeg deb package, we uses `LIBVA_DRIVER_NAME_JELLYFIN` to force VAAPI driver to avoid it being affected by other global variables, such as browser hardware acceleration.

Also the J4125 supports iHD driver without any issue, the legacy i965 driver has not been maintained since 2019, which lacks of many video processing features needed by jellyfin hwa transcoding.

**Comment by Caros2017** [comment]
Thanks a lot!

> https://github.com/jellyfin/jellyfin-ffmpeg/blob/6bd84bbf7ed35d45b67c9f45ced1adcf4f873d34/docker-build.sh#L180
> 
> With our custom ffmpeg deb package, we uses `LIBVA_DRIVER_NAME_JELLYFIN` to force VAAPI driver to avoid it being affected by other global variables, such as browser hardware acceleration.
> 
> Also the J4125 supports iHD driver without any issue, the legacy i965 driver has not been maintained since 2019, which lacks of many video processing features needed by jellyfin hwa transcoding.

Thanks a lot! I managed to solve it with:
```
    environment:
      - LIBVA_DRIVER_NAME_JELLYFIN=i965
```
I understand what you are saying about iHD driver. Unfortunately the processor goes to 100% no matter what I (and more of us) try with this driver in combination with the J4125

**Comment by nyanmisaka** [comment]
> I understand what you are saying about iHD driver. Unfortunately the processor goes to 100% no matter what I (and more of us) try with this driver in combination with the J4125

Can you share the full ffmpeg command line in your use case?

It's unlikely J4125 goes to 100% with VAAPI or QSV hardware decoding & encoding.

**Comment by nyanmisaka** [comment]
Here's another way to force the VAAPI driver at runtime:
use `-init_hw_device vaapi=va:,driver=i965 -filter_hw_device va -hwaccel_device va` to replace `-hwaccel_device /dev/dri/renderD128`

**Comment by Caros2017** [comment]
> 
> Can you share the full ffmpeg command line in your use case?
> 
> It's unlikely J4125 goes to 100% with VAAPI or QSV hardware decoding & encoding.

I had to find out how to grep the full command from `top` since I am not involved in writing frigate.

```
cat /proc/7569/cmdline
ffmpeg-hide_banner-loglevelwarning-hwaccelvaapi-hwaccel_device/dev/dri/renderD128-hwaccel_output_formatyuv420p-avoid_negative_tsmake_zero-fflags+genpts+discardcorrupt-rtsp_transporttcp-stimeout5000000-use_wallclock_as_timestamps1-irtsp://<username>:<password>@<ip>:554/live-r8-s2560x1440-frawvideo-pix_fmtyuv420ppipe
```
I hope it's readable for you without spaces.

**Comment by nyanmisaka** [comment]
```
ffmpeg -hide_banner -loglevel warning
-hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
-avoid_negative_ts make_zero -fflags+genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
-i rtsp://<username>:<password>@<ip>:554/live-r8
-s 2560x1440 -f rawvideo -pix_fmt yuv420 ppipe
```

Intel hardware decoder prefer semi-planar pixel formats such as NV12 to YUV420P if your live stream input is 8bit.

`-hwaccel_output_format yuv420p` force ffmpeg to convert NV12 hw frames to YUV420P and copy back to memory, which result in more cpu overhead during frames transfering. Change all `yuv420p` to `nv12` and see what happens.

**Comment by shred86** [comment]
I’m in the same situation with an Intel J4125 CPU. I’m seeing 100% CPU usage reported when using the iHD driver. The strange part is my CPU temperatures aren’t reflecting what 100% CPU usage would actually be, but the live video playback is very choppy (skips around). Here’s my ffmpeg command line:

````
ffmpeg-hide_banner-loglevelwarning-hwaccelvaapi-hwaccel_device/dev/dri/renderD128-hwaccel_output_formatyuv420p-avoid_negative_tsmake_zero-fflags+genpts+discardcorrupt-rtsp_transporttcp-timeout5000000-use_wallclock_as_timestamps1-irtsp://username:password@ipaddress:554/cam/realmonitor?channel=1&subtype=2-ccopy-fflvrtmp://127.0.0.1/live/back-r5-s1920x1080-frawvideo-pix_fmtyuv420ppi
````

Fortunately, forcing the i965 driver, which is what Frigate was using in its previous version, “fixes” the issue, but there appears to be something odd with Jellyfin ffmpeg and the iHD driver. Other users are reporting the same issue different CPU types so I’m not sure exactly what’s going on.

**Comment by nyanmisaka** [comment]
The only possibility is the iHD driver itself, which is built from intel's media-driver source code and does not have that problem in our use case.

**Comment by nyanmisaka** [comment]
https://github.com/intel/media-driver
I'd suggest you to report this to intel media-driver repo since it's an upstream thing.

Close this for now since there's nothing we can do to fix iHD on GeminiLake in your use case.
