### ISSUE TITLE
id3v2 multi-value Genres with separators

### ISSUE THREAD

**Issue by richlawson** [jellyfin/jellyfin-ffmpeg#172]
**Describe The Bug**
id3v2 multiple-value Genres are separated out into individual Genre tags in Jellyfin, but they are then further split out into additional Genres based on the presence of a separator (e.g., semicolon ;).

**Steps To Reproduce**
1) Import a music library in Jellyfin 10.8.1 containing mp3s with multi-value id3v2 Genres that have a separator like a semi-colon.
2) When scanning completes, there will be a Genre listed for the track for each genre, but if the multi-value fields contain a further separator (in my case, a semi-colon, that value is further split.

**Expected Behavior**
I would have expected that the string data in each multi-value Genre would be included as an individual Genre in Jellyfin without further separation, regardless of the contents of the string (i.e., including separators).

**System (please complete the following information):**

- **Platform:** Linux
- **Operating System:** Raspberry Pi OS (Debian 11 Buster, 32-bit)
- **Virtualization**: Docker
- **Jellyfin Version:** 10.8.1
- **Jellyfin-FFmpeg Version:** 5.0.1-8 (I think)
- **Hardware Acceleration:** N/A
- **CPU & GPU Model**: N/A

**MediaInfo**
Genre: `Multiple\\Value\\Genres\\This;Value\\More\\Values`
In the case above, everything works perfectly, with one Genre for each, except that `This;Value` is separated into additional Genres, "This" and "Value."

**FFmpeg Logs**
N/A

**Additional Context**
N/A

**Comment by richlawson** [comment]
Looking again at the other issues in the queue, this might be more of an enhancement. I have seen other platforms import the Genre in the way I described, though, with the same individual tracks that I've added to my Jellyfin library.

**Comment by Shadowghost** [comment]
This isn't really an ffmpeg bug. To not have a hard dependency on jellyfin-ffmpeg5 we decided to parse the multi-tags into a string when we implemented the feature, each value separated by semicolon (one of/the default separator used in Jellyfin's parser).

**Comment by richlawson** [comment]
Thank you for the context.

So is there any sort of a workaround for this (other than removing any semicolons), or are there any changes under consideration in the future?

**Comment by Shadowghost** [comment]
https://github.com/jellyfin/jellyfin/pull/7514 should take care of it by switching music tag parsing to a tagging library instead of ffprobe.

**Comment by richlawson** [comment]
Great, thank you, @Shadowghost! I'll close this out since it is unrelated to jellyfin-ffmpeg5 and keep an eye on the PR you mentioned.
