### ISSUE TITLE
VAAPI hw not working after updating to 10.8.4

### ISSUE THREAD

**Issue by Arbitrate3280** [jellyfin/jellyfin-ffmpeg#178]
**Describe The Bug**
Playback fails when trying to use vaapi hw, downgrading it to 10.8.1 works again.

**System (please complete the following information):**

- **Platform:** Linux
- **Operating System:** Latest manjaro as a host
- **Virtualization**: docker, using the linuxserver image
- **Jellyfin Version:** 10.8.4
- **Jellyfin-FFmpeg Version:** 5.1
- **Hardware Acceleration:** vaapi
- **CPU & GPU Model**: gpu 5700xt cpu 2600x

I've attached the ffmpeg log
[ffmpeg.log](https://github.com/jellyfin/jellyfin-ffmpeg/files/9333605/ffmpeg.log)

**Comment by nyanmisaka** [comment]
https://github.com/jellyfin/jellyfin-ffmpeg/releases/tag/v5.0.1-8

Can you revert jellyfin-ffmpeg to 5.0.1-8 and try again?

**Comment by Arbitrate3280** [comment]
downgrading to ffmpeg 5.0.1-8 makes it work again.

**Comment by nyanmisaka** [comment]
It seems like the updated Mesa driver is the cause. But I cannot reproduce this with Vega GPU.

**Comment by devome** [comment]
> It seems like the updated Mesa driver is the cause. But I cannot reproduce this with Vega GPU.

我用5700G自带APU在5.1-1可以复现这个问题，降级到5.0.1-8可以正常硬解。
I can reproduce this problem in 5.1-1 with the 5700g built-in APU, and it can be solved when downgraded to 5.0.1-8.

**Comment by nyanmisaka** [comment]
> > It seems like the updated Mesa driver is the cause. But I cannot reproduce this with Vega GPU.
> 
> 我用5700G自带APU在5.1-1可以复现这个问题，降级到5.0.1-8可以正常硬解。 I can reproduce this problem in 5.1-1 with the 5700g built-in APU, and it can be hard solved normally when downgraded to 5.0.1-8.

Can you try 5.1-2 from here? https://github.com/jellyfin/jellyfin-ffmpeg/actions/runs/2860341616

**Comment by devome** [comment]
> > > It seems like the updated Mesa driver is the cause. But I cannot reproduce this with Vega GPU.
> > 
> > 
> > 我用5700G自带APU在5.1-1可以复现这个问题，降级到5.0.1-8可以正常硬解。 I can reproduce this problem in 5.1-1 with the 5700g built-in APU, and it can be solved when downgraded to 5.0.1-8.
> 
> Can you try 5.1-2 from here? https://github.com/jellyfin/jellyfin-ffmpeg/actions/runs/2860341616

Yes, 5.1-2 solves this problem.

**Comment by nyanmisaka** [comment]
Thanks for the feedback. I can merge it now.
