### ISSUE TITLE
Enable builds for Ubuntu Kinetic?

### ISSUE THREAD

**Issue by satmandu** [jellyfin/jellyfin-ffmpeg#183]
Currently, the jammy builds are broken on ubuntu/kinetic/dev installs.

```
jellyfin-ffmpeg5 : Depends: libx264-163 (>= 2:0.163.3060+git5db6aa6) but it is uninstallable.
```

This is because kinetic has moved to libx264-164: https://packages.ubuntu.com/search?keywords=libx264 .

**Comment by crobibero** [comment]
Ths newest ubuntu we target is stable.
