### ISSUE TITLE
Hopes that the binary version of multiple platforms can be provided

### ISSUE THREAD

**Issue by kuai410022283** [jellyfin/jellyfin-ffmpeg#195]
Hopes that the binary version of multiple platforms can be provided

X86 amd64 arm binary version

**Comment by nyanmisaka** [comment]
FYI the portable build can be found in https://repo.jellyfin.org/releases/ffmpeg

**Comment by kuai410022283** [comment]
> FYI the portable build can be found in https://repo.jellyfin.org/releases/ffmpeg

Thank you !

**Comment by zhangbo8418** [comment]
> [仅供参考，可移植版本可以在https://repo.jellyfin.org/releases/ffmpeg](https://repo.jellyfin.org/releases/ffmpeg)中找到[](https://repo.jellyfin.org/releases/ffmpeg)
 /lib64/libm.so.6: version `GLIBC_2.27' not found

**Comment by zhangbo8418** [comment]
> [仅供参考，可移植版本可以在https://repo.jellyfin.org/releases/ffmpeg](https://repo.jellyfin.org/releases/ffmpeg)中找到[](https://repo.jellyfin.org/releases/ffmpeg)
/lib64/libc.so.6: version `GLIBC_2.27' not found

**Comment by nyanmisaka** [comment]
> [仅供参考，可移植版本可以在https://repo.jellyfin.org/releases/ffmpeg](https://repo.jellyfin.org/releases/ffmpeg)中找到
> /lib64/libc.so.6: version `GLIBC_2.27' not found

https://github.com/jellyfin/jellyfin-ffmpeg/tree/jellyfin/builder#targets-variants-and-addins

Required glibc version:

> linux64 (x86_64 Linux, glibc>=2.23, linux>=4.4)

> linuxarm64 (arm64 (aarch64) Linux, glibc>=2.27, linux>=4.15)

**Comment by zhangbo8418** [comment]
> > [仅供参考，可移植版本可以在https://repo.jellyfin.org/releases/ffmpeg](https://repo.jellyfin.org/releases/ffmpeg)中找到
> > /lib64/libc.so.6: version `GLIBC_2.27' not found
> 
> https://github.com/jellyfin/jellyfin-ffmpeg/tree/jellyfin/builder#targets-variants-and-addins
> 
> Required glibc version:
> 
> > linux64 (x86_64 Linux, glibc>=2.23, linux>=4.4)
> 
> > linuxarm64 (arm64 (aarch64) Linux, glibc>=2.27, linux>=4.15)

That means it can't be used....
