### ISSUE TITLE
When Arabic UTF-8 subtitles are burned into the video, it does not look as it should

### ISSUE THREAD

**Issue by 0TTA** [jellyfin/jellyfin-ffmpeg#217]
**Describe The Bug**

When Arabic UTF-8 subtitles are burned into the video, it does not look as it should.

**Steps To Reproduce**
1. Make an Arabic subtitle file, either ASS or SRT, and write in it: "!هَذَا اَلنَّصِّ هُوَ مِثَالٌ لِنَصِّ".
2. Let Jellyfin transcode it.
3. It doesn’t occur with all fonts, though, but it does with most of them. Adobe Arabic, for example, works perfectly. I use Calibri, which it doesn't.

**Expected Behavior**

It should look like it's showing in MPV Player:

![MPV Player](https://user-images.githubusercontent.com/82990310/216150243-f989ecff-94bc-4970-8d59-37ecfee30f55.png)

**System:**

- **Platform:** Linux
- **Operating System:** 5.10.28-Unraid
- **Virtualization**: Docker
- **Jellyfin Version:** 10.8.9
- **Jellyfin-FFmpeg Version:** 5.1.2-Jellyfin

**Additional Context**
I spent some time trying to figure out the reasoning behind this and concluded the following:

First, let's see what exactly the problem is, because if you are not an Arabic speaker, you might not get what the problem is.

This is a screenshot from MPV Player (not burned):

![MPV Player](https://user-images.githubusercontent.com/82990310/216150243-f989ecff-94bc-4970-8d59-37ecfee30f55.png)

And the following one is the result of the following command (it should not look like this):

     /usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -init_hw_device cuda=cu:0 -filter_hw_device cu -autorotate 0 -i "/config/test.mp4" -codec:v:0 h264_nvenc -pix_fmt yuv420p -vf "subtitles=f=/config/test.ass:charenc=utf-8:fontsdir=" -an -y /config/test.new.mp4

![subtitles](https://user-images.githubusercontent.com/82990310/216153017-9d765b07-60ca-4571-a700-322de460cbde.png)

I hope now you can see the issue.

Now, I'll show you a fix I found that, unfortunately, only works with the ASS format:

If we replaced:

     -vf "subtitles=f=/config/test.ass:charenc=utf-8:fontsdir="

with

     -vf "ass=/config/test.ass:shaping=complex"

the problem will go away. Like, when I do the next command:

     /usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -init_hw_device cuda=cu:0 -filter_hw_device cu -autorotate 0 -i "/config/test.mp4" -codec:v:0 h264_nvenc -pix_fmt yuv420p -vf "ass=/config/test.ass:shaping=complex" -an -y /config/test.new.mp4

It works amazingly well, like in the next screenshot (burned):

![burned](https://user-images.githubusercontent.com/82990310/216157159-04a9b7a4-e0f8-4628-83a6-e2be49653826.png)

The downside with this workaround is that it only works with ASS, which means I did not find a solution for SRT but another workaround, which is to convert the SRT to ASS in the background, and then start the transcoding. But I don't know if this is sufficient.

I'm currently using another workaround, which is that I found a font called Adobe Arabic that does not have this issue. Then I mapped it to /usr/share/fonts and renamed it (Calibri), which is the font I prefer and which is used in all my library. Now, this problem doesn't occur. Because when it's transcoding, it uses the previous font, Which is (Adobe Arabic), but I don't like the font for so many reasons. One of them is that it is not the same size as (Calibri). As a result, I like it when I watch without transcoding and it uses the font (Calibri), because it's not burned in and the font is installed on my device. But when it's transcoded, it's so small. But it works for now.

I have also tried every font I like, yet this issue occurs with all of them.

Thanks!

**Comment by nyanmisaka** [comment]
Can you share an ASS and SRT subtitle that includes this sentence?

**Comment by 0TTA** [comment]
Of course.

[Script Info]
PlayResX: 384
PlayResY: 288
ScriptType: v4.00+
PlayDepth: 0
ScaledBorderAndShadow: Yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Calibri,42,&H00FFFFFF,&H00FFFFFF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,1,0,2,30,30,30,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:01.00,0:16:40.00,Default,,0,0,0,,‫هَذَا اَلنَّصِّ هُوَ مِثَالٌ لِنَصِّ!

**Comment by 0TTA** [comment]
> Can you share an ASS and SRT subtitle that includes this sentence?


Of course.

ASS file:

[Script Info]
PlayResX: 384
PlayResY: 288
ScriptType: v4.00+
PlayDepth: 0
ScaledBorderAndShadow: Yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Calibri,42,&H00FFFFFF,&H00FFFFFF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,1,0,2,30,30,30,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:01.00,0:16:40.00,Default,,0,0,0,,‫هَذَا اَلنَّصِّ هُوَ مِثَالٌ لِنَصِّ!


SRT file:

1
00:00:01,000 --> 00:16:40,000
‫هَذَا اَلنَّصِّ هُوَ مِثَالٌ لِنَصِّ!

Is this okay enough? I can't upload an ASS file, copy it to a TXT file, and change TXT to ASS; same with SRT.
Thank you for the response!

**Comment by nyanmisaka** [comment]
It seems to be a font shaper issue in [fribidi](https://github.com/fribidi/fribidi), which is the default simple and faster one used by the `vf_subtitles` and `vf_ass` filter. While the complex one uses [harfbuzz](https://github.com/harfbuzz/harfbuzz) as its shaper so it can bypass this issue.

Can you tell me which is the correct one for you? Both are rendered from SRT. (1: harfbuzz, 2: fribidi)
![image](https://user-images.githubusercontent.com/14953024/216420204-038512e2-3e3f-4011-8c39-9d9b88424171.png)

And here's what I see from my browser, which looks similar to the first one above. I don't know if it's correct though.
![image](https://user-images.githubusercontent.com/14953024/216421126-7acf48c4-a265-47dc-abbb-1f4ed7a2ea76.png)

**Comment by 0TTA** [comment]
> Can you tell me which is the correct one for you?

The first is the correct one.

> And here's what I see from my browser, which looks similar to the first one above. I don't know if it's correct though.

Yes, it is correct.

> It seems to be a font shaper issue in [fribidi](https://github.com/fribidi/fribidi), which is the default simple and faster one used by the vf_subtitles and vf_ass filter. While the complex one uses [harfbuzz](https://github.com/harfbuzz/harfbuzz) as its shaper so it can bypass this issue.

I'm not knowledgeable enough to understand what that means.

**Comment by nyanmisaka** [comment]
We can add an option in Jellyfin to allow you choose shaping method and patch our ffmpeg to add the shaping option for the subtitles filter that used by SRT.

Can you file an issue to libass and fribidi repos so as they can find the root cause and fix it in the upstream? You can explain this better than me.

**Comment by 0TTA** [comment]
> We can add an option in Jellyfin to allow you choose shaping method and patch our ffmpeg to add the shaping option for the subtitles filter that used by SRT.

That would be so nice! But this too occurs with ASS, because Jellyfin uses `vf_subtitles` for both SRT and ASS. So you might need to start using `vf_ass` for ASS? I don't know.

> Can you file an issue to libass and fribidi repos so as they can find the root cause and fix it in the upstream? You can explain this better than me.

Of course.

**Comment by nyanmisaka** [comment]
vf_subtitles can handle both SRT and ASS but it lacks the shaping option. Our patched ffmpeg will enable this option for it so as Jellyfin can use `subtitles=sub.srt:shaping=complex`.
