### ISSUE TITLE
Can't build with zvbi 0.2.40

### ISSUE THREAD

**Issue by Technetium1** [jellyfin/jellyfin-ffmpeg#220]
**Describe The Bug**
Tried building with `jellyfin-ffmpeg5` [from the AUR](https://aur.archlinux.org/packages/jellyfin-ffmpeg5) by @nyanmisaka. It fails with:
`ERROR: zvbi-0.2 not found using pkg-config`

[The dependency is correctly specified](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=jellyfin-ffmpeg5#n46), but the version seems not valid to use per: 
https://github.com/jellyfin/jellyfin-ffmpeg/blob/52193bee1c05466630f1177ed17764ea4145e6b3/configure#L6681
Is this the intended failure for a mismatched version, or should it work?

**Steps To Reproduce**
- Attempt to build with `zvbi 0.2.40`

**Expected Behavior**
A successful build with `zvbi 0.2.x`. According to [semver](https://semver.org/) there should be no breaking changes.

**System (please complete the following information):**

- **Platform:** Linux
- **Operating System:** Arch (Garuda)
- **Virtualization**: None
- **Jellyfin Version:** N/A
- **Jellyfin-FFmpeg Version:** 5.1.2-7
- **Hardware Acceleration:** N/A
- **CPU & GPU Model**: Ryzen 9 3900XT / Radeon RX 6700 XT

**Comment by nyanmisaka** [comment]
https://bugs.archlinux.org/task/77452?project=1&string=zvbi

https://github.com/zapping-vbi/zvbi/issues/40

zvbi 0.2.41 fixed the issue.

**Comment by Technetium1** [comment]
Thank you very much! :tada:
