### ISSUE TITLE
Transcoding streams

### ISSUE THREAD

**Issue by ghost** [jellyfin/jellyfin-ffmpeg#229]
Sorry if this was previously asked. I always wonder why my jellyfin TV stream would start transcoding but the same stream plays just fine on VLC? Both share the same codec library right? I have come to experience that many times.
Could someone give me an answer?

**Comment by Bond-009** [comment]
Please ask in the correct repo and with some more information (media info, client info, etc)
https://github.com/jellyfin/jellyfin-androidtv
