### ISSUE TITLE
jellyfin-ffmpeg6 package for archlinux

### ISSUE THREAD

**Issue by Aljutor** [jellyfin/jellyfin-ffmpeg#237]
Can we have jellyfin-ffmpeg6 package in archlinux aur? 
And it would be nice to have  jellyfin-ffmpeg-git tracking master for testing purposes.

**Comment by Aljutor** [comment]
Sorry for the wrong label

**Comment by nyanmisaka** [comment]
> 6.0 version is NOT fully compatible with Jellyfin 10.8.9, which means Jellyfin 10.8.10 or newer is required.

I've been holding back the PKGBUILD of 6.0 for this reason.

**Comment by nyanmisaka** [comment]
https://aur.archlinux.org/packages/jellyfin-ffmpeg6

https://aur.archlinux.org/packages/jellyfin-ffmpeg6-bin
