### ISSUE TITLE
Cant safely remove jellyfin-ffmpeg5 before upgradation to ffmpeg6

### ISSUE THREAD

**Issue by serialpotato** [jellyfin/jellyfin-ffmpeg#243]
Hi. I am trying to install jellyfin-ffmpeg6. The jellyfin server version is 10.8.10. To ensure the usage of newest ffmpeg6, I purged the ffmpeg5, which surprisingly also removed the jellyfin server when it should only remove ffmpeg5 package. Afterwards, I installed ffmpeg6 but the installation log suggested jellyfin packages are no longer required and I should autoremove them. This further indicates that the jellyfin server was removed during the purge. 

Here are my logs with steps to reproduce it:

```
apt purge jellyfin-ffmpeg5
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  at jellyfin-server jellyfin-web libaacs0 libass9 libbdplus0 libbluray2 libmp3lame0 libmpg123-0 libopenmpt0 libtheora0 libudfread0 libvpx7 libx264-163 libzvbi-common libzvbi0
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  jellyfin* jellyfin-ffmpeg5*
0 upgraded, 0 newly installed, 2 to remove and 0 not upgraded.
After this operation, 28.4 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 204357 files and directories currently installed.)
Removing jellyfin (10.8.10-1) ...
Removing jellyfin-ffmpeg5 (5.1.3-1-jammy) ...
Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
(Reading database ... 204315 files and directories currently installed.)
Purging configuration files for jellyfin-ffmpeg5 (5.1.3-1-jammy) ...
root@instance-20230403-1604:/var/lib# apt install jellyfin-ffmpeg6
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  at jellyfin-server jellyfin-web
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  jellyfin-ffmpeg6
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 11.0 MB of archives.
After this operation, 28.6 MB of additional disk space will be used.
Get:1 https://fra1.mirror.jellyfin.org/ubuntu jammy/main arm64 jellyfin-ffmpeg6 arm64 6.0-2-jammy [11.0 MB]
Fetched 11.0 MB in 1s (17.3 MB/s)
ydebconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package jellyfin-ffmpeg6.
(Reading database ... 204315 files and directories currently installed.)
Preparing to unpack .../jellyfin-ffmpeg6_6.0-2-jammy_arm64.deb ...
Unpacking jellyfin-ffmpeg6 (6.0-2-jammy) ...
Setting up jellyfin-ffmpeg6 (6.0-2-jammy) ...
Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
Scanning processes...
```

However, the server somehow continues to work. Its only when I try to install jellyfin again, I get the error that the jellyfin is broken:

```

root@instance-20230403-1604:/var/lib# apt install jellyfin
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 jellyfin-ffmpeg6 : Conflicts: jellyfin-ffmpeg5 but 5.1.3-1-jammy is to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
```

The apt purge command should only remove jellyfin-ffmpeg5 and not render the jellyfin installation beyond repair that a new installation from scratch is needed. 

Here are system specs:

OS: Ubuntu 22.04.2 LTS aarch64
Host: KVM Virtual Machine virt-4.2
Jellyfin Version: 10.8.10
Jellyfin-ffmpeg: 6.0 version
CPU: ARM64
GPU: None

Please help

**Comment by joshuaboniface** [comment]
That resolution is fine. You can just remove the `jellyfin` metapackage, it's just there to aid installing `jellyfin-server`, `jellyfin-web`, and `jellyfin-ffmpeg`, and contains no actual data/configs/etc. itself. You will want to mark the others as manually installed though.

```
sudo apt remove --yes jellyfin
sudo apt install --yes jellyfin-server jellyfin-web at
sudo apt remove --yes jellyfin-ffmpeg5
sudo apt install --yes jellyfin-ffmpeg6
```

Will get you to where you expect.

**Comment by serialpotato** [comment]
Thank you. I just did above and tried "apt install jellyfin" again but I am still seeing the error about broken jellyfin package:

```
root@instance-20230403-1604:/home/ubuntu# apt install jellyfin
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 jellyfin-ffmpeg6 : Conflicts: jellyfin-ffmpeg5 but 5.1.3-1-jammy is to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
```
Shouldn't it say the latest version is already installed?

**Comment by joshuaboniface** [comment]
You do not want to install `jellyifn`. `jellyfin` is just a metapackage, which is a[n empty] package that purely exists to have `Depends:` entries on other packages and force them to be installed. So `jellyfin` exists to quickly and easily pull in `jellyfin-server`, `jellyfin-web`, and `jellyfin-ffmpeg5` and simplify the basic initial install command (`apt install jellyfin` is easier to type and understand than `apt install jellyfin-server jellyfin-web jellyfin-ffmpeg5`), but doesn't do anything on its own. 

But bcause of that dependency requirement, the `jellyfin` metapackage will try to install `jellyfin-ffmpeg5`, which conflicts with `jellyfin-ffmpeg6`, which you do not want. You do not need `jellyfin` installed to have, use, or update Jellyfin, the actual program is in those other packages mentioned, so best to just leave that uninstalled. Everything else will work fine.
