### ISSUE TITLE
Package jellyfin is missing dependency for jellyfin-ffmpeg6

### ISSUE THREAD

**Issue by zapotah** [jellyfin/jellyfin-ffmpeg#250]
**Describe The Bug**
The jellyfin metapackage (at least on ubuntu 20.04) is missing the dependency jellyfin-ffmpeg6 which makes apt remove it on installing jellyfin-ffmpeg6

**Steps To Reproduce**
Install jellyfin-ffmpeg6 on ubuntu 20.04

**Expected Behavior**
Metapackage jellyfin has proper dependencies and doesnt get removed

**System (please complete the following information):**

- **Platform:** Linux
- **Operating System:** Ubuntu 20.04
- **Virtualization**: KVM
- **Jellyfin Version:** 10.8.10
- **Jellyfin-FFmpeg Version:** 6.0-3-focal
- **Hardware Acceleration:** N/A
- **CPU & GPU Model**: AMD EPYC 7502P

**Comment by nyanmisaka** [comment]
@zapotah See https://github.com/jellyfin/jellyfin-ffmpeg/issues/243#issuecomment-1520543283
