### ISSUE TITLE
Dependency issue with latest  intel-media-drive

### ISSUE THREAD

**Issue by Aljutor** [jellyfin/jellyfin-ffmpeg#266]
On Archlinux 

Current aur package ijellyfin-ffmpeg6 conflicts with latest intel-media-drive-git 

```
error: failed to prepare transaction (could not satisfy dependencies)
:: installing libplacebo (5.264.1-1) breaks dependency 'libplacebo.so=229-64' required by jellyfin-ffmpeg6
 -> error installing repo packages
```

**Comment by nyanmisaka** [comment]
Whenever `libplacebo` gets update, you should re-compile `jellyfin-ffmpeg6`.
Or you can switch to `jellyfin-ffmpeg6-bin` instead.
