### ISSUE TITLE
If HDR tone mapping is not used, devices that support HDR cannot recognize HDR.

### ISSUE THREAD

**Issue by shaino** [jellyfin/jellyfin-ffmpeg#282]
Did ffmpeg ?

**Comment by shaino** [comment]
HDR videos that disable transcoding or use transcoding encapsulation can be played on the device.
Once transcoding is done, the device will no longer be able to recognize HDR videos.

**Comment by nyanmisaka** [comment]
Currently we only transcode to SDR. HDR-to-HDR transcoding is already planned, but not the first priority.

**Comment by shaino** [comment]
HDR videos that disable transcoding or use transcoding encapsulation can be played on the device.
Once transcoding is done, the device will no longer be able to recognize HDR videos.

**Comment by shaino** [comment]
> 目前我们只转码为 SDR。HDR 到 HDR 转码已经在计划中，但不是第一要务。

Great
