### ISSUE TITLE
https protocol not found, recompile FFmpeg with openssl, gnutls or securetransport enabled.

### ISSUE THREAD

**Issue by bin101** [jellyfin/jellyfin-ffmpeg#290]
I would like to stream some public/legal m3u live tv m3u stream in Germany but sadly ffmpeg is currently build without https support so I only receive this error:

`
https protocol not found, recompile FFmpeg with openssl, gnutls or securetransport enabled.
`

Would it be possible to provide a jellyfin-ffmpeg version with https support?

**Comment by nyanmisaka** [comment]
Please share the full FFmpeg log so as I can know which version you are using.

**Comment by bin101** [comment]
@nyanmisaka Sure, here it is:

`ffmpeg version 6.0-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (crosstool-NG 1.25.0.152_89671bf)
  configuration: --prefix=/ffbuild/prefix --pkg-config=pkg-config --pkg-config-flags=--static --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --extra-version=Jellyfin --extra-cflags= --extra-cxxflags= --extra-ldflags= --extra-ldexeflags=-pie --extra-libs=-ldl --enable-gpl --enable-version3 --enable-lto --disable-ffplay --disable-debug --disable-doc --disable-ptx-compression --disable-sdl2 --disable-libxcb --disable-xlib --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-amf --enable-chromaprint --enable-libdav1d --enable-libfdk-aac --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvpx --enable-libwebp --enable-libvpl --enable-libopenmpt --enable-libsrt --enable-libsvtav1 --enable-libdrm --enable-vaapi --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libzimg --enable-libzvbi
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
https protocol not found, recompile FFmpeg with openssl, gnutls or securetransport enabled.
https://derste247liveint.akamaized.net/hls/live/662735/daserste_int/master.m3u8: Protocol not found
Did you mean file:https://derste247liveint.akamaized.net/hls/live/662735/daserste_int/master.m3u8?`

**Comment by nyanmisaka** [comment]
@bin101 Next release [6.0-7](https://github.com/jellyfin/jellyfin-ffmpeg/pull/283) will enable openssl 3.x in Linux portable builds.
