### ISSUE TITLE
ffmpeg not found

### ISSUE THREAD

**Issue by SinoX1337** [jellyfin/jellyfin-ffmpeg#305]
In  /usr/lib/jellyfin-ffmpeg/ffmpeg i dont have it installed, how i can install it?

**Comment by SinoX1337** [comment]
I installed it with the site : https://jellyfin.org/docs/general/installation/linux#ffmpeg-installation

Its installed but i cant find it at there:
"/usr/share/jellyfin-ffmpeg"

**Comment by VampiricAlien** [comment]
I have mine install at `/usr/lib/jellyfin-ffmpeg/ffmpeg`

You could install the file to `/usr/bin/ `and have it system wide.

**Comment by nyanmisaka** [comment]
The path may vary by distro, but should generally match `/usr/*/jellyfin-ffmpeg/ffmpeg`.
