### ISSUE TITLE
jellyfin-ffmpeg for armhf assumes Raspberry Pi device

### ISSUE THREAD

**Issue by ghost** [jellyfin/jellyfin-ffmpeg#32]
Hi, trying to run jellyfin on an Odroid XU4 running Ubuntu 18.04.4 LTS. When installed, jellyfin pulls in jellyfin-ffmpeg and installs it. Attempting to play back video that requires transcoding results in many errors such as:
```
[2020-03-22 07:14:17.676 +00:00] [ERR] Error in "ffprobe"
System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
```
When I attempt to run jellyfin-ffmpeg manually, it dies due to a missing dependency:
```
root@odroid:/var/log/jellyfin# /usr/lib/jellyfin-ffmpeg/ffmpeg
/usr/lib/jellyfin-ffmpeg/ffmpeg: error while loading shared libraries: libmmal_core.so: cannot open shared object file: No such file or directory
``` 

As far as I can tell, libmmal_core.so only exists on the Raspberry Pi platform. Why is the armhf build of jellyfin-ffmpeg depending upon a raspberry pi only library?

**Comment by JustAMan** [comment]
While depending on a Raspberry Pi-only library isn't ideal (and I marked this issue as a bug), let's face the fact that RPi is probably the typical `armhf` CPU running Jellyfin out there (others are very scarce).

For you to mitigate the issue, you can always install some other ffmpeg (even system one) which is 4.0 or newer, and tell Jellyfin to use that.

**Comment by ghost** [comment]
"others are very scarce"

Agree to disagree on that. There's a LOT of armhf devices out there that aren't Pi.

**Comment by ferferga** [comment]
@zerojay Any idea on how we can solve this without removing MMAL support?

Take in mind that, afaik, this only should happen when OMX acceleration is enabled.

**Comment by JustAMan** [comment]
It is relatively easy to implement a stub `libmmal_core.so` with all exported symbols that would load but not work when called, if that helps.

**Comment by ferferga** [comment]
@JustAMan It's strange though that it requires it when other implemented functions doesn't crash ffmpeg at all.

[This is a nice solution as well](https://github.com/linuxserver/docker-jellyfin/commit/2250cedb34defffb87d97fb5fe6e7e7df6d2d77a)

**Comment by JustAMan** [comment]
I don't know the license for those files... and I cannot find any source files for `libraspberrypi0` anyway.

**Comment by rigtorp** [comment]
libmmal_core.so is a binary from from https://github.com/raspberrypi/firmware/tree/master/hardfp/opt/vc/lib
https://github.com/raspberrypi/firmware/blob/master/hardfp/opt/vc/LICENCE

**Comment by Tonymac32** [comment]
I'm also running into this, XU4.

**Comment by vallode** [comment]
> @zerojay Any idea on how we can solve this without removing MMAL support?
> 
> Take in mind that, afaik, this only should happen when OMX acceleration is enabled.

This happens to me regardless of hardware acceleration options. 

Odroid XU4
Armbian bullseye with Linux 5.4.28-odroidxu4

EDIT: For people facing this issue on Odroids (Armbian), I just installed the `ffmpeg` package and pointed jellyfin to it. Playback -> FFmpeg path -> `/usr/bin/ffmpeg`

**Comment by Tonymac32** [comment]
@vallode thanks, I also got that far, however that is only allowing direct playback to function.  Far better than the complete lack of operation I had before, but the hardware acceleration is still no there.

@teacupx this is out of my knowledge area, do you have an idea?  (Sorry to invoke you randomly, but I think you might be the guy who would know)

**Comment by teacupx** [comment]
@Tonymac32  My pleasure!

A workaround for being able to use jellyfin-ffmpeg is to download all libs from "https://github.com/raspberrypi/firmware/tree/master/hardfp/opt/vc/lib" and copy them to "/usr/lib/" . But still, I found XU4 hardware accel to be very unstable with the default jellyfin-ffmpeg.

My recommendation for XU4 users is to use the patched ffmpeg from https://github.com/mihailescu2m/FFmpeg. It's an older version, but works like a charm. To compile, make sure you uncomment the deb-src sources in /etc/apt/sources.list, and then:
`apt update`
`apt build-dep ffmpeg`
`apt install fakeroot git`
`git clone https://github.com/mihailescu2m/FFmpeg`
`cd FFmpeg`
`dpkg-buildpackage -us -uc -b -j8 -rfakeroot`

It will take a while to build. I recommend doing it in a clean installation on a spare SD card, to avoid messing up your main system with many package installations.

**Comment by Tonymac32** [comment]
@teacupx I'm getting an error about opencv not found using pkg-config

I see 2 things that need figured out.

- What is needed to decouple the dependency on a downright evilly licensed library (technically the workaround of downloading these files to simply make this ffmpeg happy breaks the law in a few countries)

Specifically, from the previously linked license:

`* This software may only be used for the purposes of developing for, 
  running or using a Raspberry Pi device.`

and (outside the scope of this issue until the first is resolved)

- How to move the patches on @teacupx 's recommended ffmpeg to the modern one so maybe the advertised acceleration works smoothly
----
For the first, perhaps the project could simply package 2 ffmpegs, one for RPi with it's rather nasty closed-source binary blob licensing and one for everyone else.  Then it picks the one with anti-libre-software dependencies if someone clicks on hardware accel for RPi.  I don't know what compilation options/switches could do here, whether there's something on the userspace side that would make this a non-issue.  This is outside the realm of device trees and bootloaders I usually work within.  

For the second, if I've the time and energy I could start piecing some of that together.  There are some patches there that look like basic housekeeping, only a couple seem to directly impact the exynos MFC, and they seem very straightforward (a wrong number of buffers seems plausible for stability issues, for example)

@teacupx I happen to be setting up a new clean server, it prompted me to try this out, so I'll get building.

**Comment by rgabbo** [comment]
Not limited to Odroid. I get same error on ASUS Tinker Board (armv7l). HW accelleration is disabled.
DietPi (Armbian) with Linux 4.19.57-rockchip

**Comment by euphoria360** [comment]
Also on banana pi with mainline debian 10 on it.

Im trying to install ffmpeg manually and point jellyfin to it, to see if anyzthing changes...

**Comment by meaninglessvanity** [comment]
I was having trouble getting the music scanner to pick up metadata tags until I installed ffmpeg from my distro (Debian) and then symlinked /usr/lib/jellyfin-ffmpeg/ffmpeg to /usr/bin/ffmpeg.  Same deal for ffprobe

Again, this worked for Debian on Tinkerboard S.  YMMV.

**Comment by hauntingEcho** [comment]
I'm seeing this issue as well, running on a Helios4

**Comment by cyberia-ng** [comment]
> I was having trouble getting the music scanner to pick up metadata tags until I installed ffmpeg from my distro (Debian) and then symlinked /usr/lib/jellyfin-ffmpeg/ffmpeg to /usr/bin/ffmpeg. Same deal for ffprobe

You can change the ffmpeg location in the admin settings, and the ffprobe location is computed by essentially doing a `s/mpeg$/probe/` on the ffmpeg path. So if you installl system ffmpeg and point to `/usr/bin/ffmpeg` in your admin settings, it will also use `/usr/bin/ffprobe` for metadata extraction.
