### ISSUE TITLE
Transition to jellyfin-ffmpeg6

### ISSUE THREAD

**Issue by Gauvino** [jellyfin/jellyfin-ffmpeg#321]
@nyanmisaka Hello, I don't know if it's you are Joshua who maintains this repo https://repo.jellyfin.org/releases/server/windows/versions/jellyfin-ffmpeg/6.0.1-1/ or here
https://repo.jellyfin.org/releases/server/windows/ffmpeg/
But for the 6.0 release there is no portable available so if you can release them so I can change the url in the build script of Jellyfin

**Comment by nyanmisaka** [comment]
This is intentional behavior. There are some breaking changes (Nvidia driver version) in jellyfin-ffmpeg6 so we postponed to enable it and leave it to JF 10.9 releases. See https://github.com/jellyfin/jellyfin-ffmpeg/commit/dba214cbbb513d2c62f427c34e547c5db5c4f6b9
