### ISSUE TITLE
Development based on jellyfin-ffmpeg

### ISSUE THREAD

**Issue by iGwkang** [jellyfin/jellyfin-ffmpeg#324]
Hello, I would like to inquire about how to modify the compilation script to build individual libraries such as avcodec, avformat, swscale, etc., when developing based on the jellyfin-ffmpeg library. Currently, when I execute the `build-linux-amd64` script, it only generates the ffmpeg executable without the corresponding library and include files. Could you please provide guidance on the necessary modifications to the build script for generating these libraries separately?

**Comment by nyanmisaka** [comment]
@iGwkang Goto https://github.com/jellyfin/jellyfin-ffmpeg/tree/jellyfin/builder and read the README.md.

**Comment by iGwkang** [comment]
@nyanmisaka Is it allowed to specify gcc version? and i want to use static library

**Comment by nyanmisaka** [comment]
Not currently supported. But you can achieve this by modifying this file.

https://github.com/jellyfin/jellyfin-ffmpeg/blob/jellyfin/builder/images/base-linux64/ct-ng-config

**Comment by iGwkang** [comment]
I changed it for a day, but it always reported an error when compiling. When I changed gcc to version 7.5, it said that -lpthread could not be found. This is too time-consuming. I have to regenerate the docker image every time. Can you help me?
@nyanmisaka 
```
CT_LINUX_V_3_10=y
CT_LINUX_VERSION="3.10.108"
CT_GLIBC_V_2_17=y
CT_GLIBC_VERSION="2.17"
CT_GCC_V_7=y
CT_GCC_VERSION="7.5.0"
```
`FF_CONFIGURE+=" --enable-static --disable-shared"` in `defaults-gpl-shared.sh`
