### ISSUE TITLE
Arch Linux Package Out of Date by about 2 months

### ISSUE THREAD

**Issue by Lucas-V-L** [jellyfin/jellyfin-ffmpeg#325]
preface: not sure if this is the right place to report this, but i noticed the arch package was already flagged out of date 2 months ago with no action, so i figured id ask here.

**Describe The Bug**
Out of date package on Arch Linux to the point where installation is impossible with regular ffmpeg also installed (which other things depend on, so i cant just remove that). specifically the issue is that the out of date version of jellyfin-ffmpeg depends on an old version of libplacebo and regular ffmpeg depends on a new one.

**Steps To Reproduce**
try to install jellyfin-ffmpeg on an arch linux system with ffmpeg installed

**Expected Behavior**
it installs with no issue

**System (please complete the following information):**

- **Platform:** Linux
- **Operating System:** Arch Linux (fully updated as of writing)
- **Virtualization**: none
- **Jellyfin Version:** 10.8.10
- **Jellyfin-FFmpeg Version:** does not install
- **Hardware Acceleration:** none, because it refuses to install
- **CPU & GPU Model**: AMD Ryzen 7 3700x & AMD RX580

**MediaInfo**
N/A

**Logs**
trying to install jellyfin-ffmpeg returns the following:
```
[lucas@lucasvl-pc ~]$ sudo pacman -S jellyfin-ffmpeg
[sudo] password for lucas: 
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing libplacebo (5.264.1-4) breaks dependency 'libplacebo.so=338-64' required by ffmpeg

```
**Additional Context**
if this is the wrong place to report this, please let me know where to go and i will go there.
i have already tried manually installing the specified version of libplacebo with no success.
here is the package page - https://archlinux.org/packages/extra/x86_64/jellyfin-ffmpeg/ - i do not have an account to report a bug directly on the package and cannot make one.

**Comment by nyanmisaka** [comment]
@Lucas-V-L 
`jellyfin-ffmpeg` isn't an AUR package anymore. I have no access to push updates to it now. So the timeliness of updates depends on [community maintainers](https://github.com/jellyfin/jellyfin/issues/10315#issuecomment-1744330563).

Generally speaking, you only need to edit the jellyfin-ffmpeg version in the PKGBUILD and rebuild the package with `makepkg -si`.

**Comment by grawlinson** [comment]
This issue only happens when testing repository is enabled, it doesn’t happen otherwise.

Additonally, the package is out of date because it fails to build from source and I haven’t had time to look into it.

**Comment by ebkalderon** [comment]
Good news! The `extra` package has been updated to version 6.0.1-1 (the current latest) since this issue was created.

**Comment by Lucas-V-L** [comment]
it appears to indeed be fixed! ill close this issue now :)
