### ISSUE TITLE
Improve tone mapping performance on Apple Silicon

### ISSUE THREAD

**Issue by gnattu** [jellyfin/jellyfin-ffmpeg#357]
Currently, for the 10.9 release, we are using OpenCL as a fallback for Video Tone Mapping in addition to VideoToolbox's native mechanism to support Dolby Vision Profile 5 Videos. It works, but the performance is very underwhelming on Apple Silicon GPUs. A 24-core M1 Max GPU can barely tone map 4K30 DoVi P5 videos.

One problem is the use of hardware surface. The current hardware mapping route between OpenCL and VideoToolbox is very slow. The `hwmap` and reverse `hwmap` chain significantly slows down the operation on 4K videos. By disabling the hardware surface and using `hwupload` and `hwdownload`, we could boost performance by almost 80% on a 4K video (52fps vs. 29fps).

The other problem stems from the GPU architecture itself and Apple's deprecation of OpenCL. The Apple GPU was designed to have slower communication between SIMD groups in a thread group but faster communication within a single SIMD. This tradeoff improves power efficiency and requires modifying algorithms to utilize SIMD-scoped operations. In OpenCL, Apple does not expose such operations to the shading language because they officially deprecated OpenCL, and this restriction fundamentally makes some OpenCL code bases slower than if written in Metal, including our OpenCL tone mapping kernels. It also makes matrix multiplication drop to 1/3 of maximum performance, becoming almost no faster than the CPU's AMX. By using libplacebo over the low-overhead MoltenVK, we can get another 80% performance boost (93 vs. 52) by using `hwupload`/`hwdownload`. The hwmap route is not implemented yet, but such performance improvement is already significant because this means with a powerful enough GPU, libplacebo can outperform VideoToolbox's native tone-mapping at the cost of higher power consumption.

To make this happen, we need to figure out a way to actually ship these binaries. ffmpeg loads Vulkan libs by `dlopen`, which means we need to ship `libMoltenVK.dylib` or let the user install it. Our portable builds will still be "portable" because they would run without MoltenVK, but they just cannot use libplacebo, which is in a similar situation as a Linux machine with a not correctly configured GPU driver. The configuration would be much simpler than configuring a Linux GPU, though. Just placing the `libMoltenVK.dylib` into the same folder as `ffmpeg` would be enough.

The next thing would be trying to implement a hwmap route to see if it improves performance further, but at this point, I have no confidence in `videotoolbox_vld` hardware surface. It is already broken in all our current use cases, and I don't expect it would work properly with Vulkan either, but I will try it.

I plan to migrate to libplacebo in the 10.10 release, and maybe implement some workaround to the current OpenCL filter on Apple silicon, like disabling hardware surface and/or force a quality tradeoff.

**Comment by nyanmisaka** [comment]
Maybe porting `tonemap_opencl` to `tonemap_videotoolbox` is also a path? Our use case does not require the fancy features in `libplacebo` (as its name placebo suggests), however from my experience `libplacebo` constantly refactors their API to the point of breaking existing functionality (ff 6.1/master + hwmap broken, `libplacebo` master black screen when importing `p010le` vaapi/drm frame). I've been bitten so many times that I've changed my mind so I'm not sure if it's still worth the risk of the time for a new implementation.

**Comment by gnattu** [comment]
> Maybe porting `tonemap_opencl` to `tonemap_videotoolbox` is also a path? 

Yes, it is an option, but it would require more work than using `libplacebo`

>  I've been bitten so many times that I've changed my mind so I'm not sure if it's still worth the risk of the time for a new implementation.

Actually, the problems you mentioned sound very "Vulkan" to me, and perhaps not specific to libplacebo, but rather the risks you have to take if you want to use anything Vulkan. For the VideoToolbox case, the `hwmap` or hardware frame issue is not as severe as on other platforms because the hardware frame implementation is broken enough that we already avoid using it in most cases anyway, which even perform worse than just using `hwupload/hwdownload`. That means we always have the option to use libplacebo without `hwmap` for VideoToolbox if implementing a new `hwmap` is too prone to breaking.

We have plenty of time to try each route, and if a full Metal port does not succeed (either it's not finished or not performant enough) before the 10.10 feature freeze, we could still use libplacebo without `hwmap` as a backup plan.

**Comment by nyanmisaka** [comment]
It is not the fault of `vf_hwmap.c` itself, they are caused by issues in `vf_libplacebo.c` (maybe hwcontext_vulkan infra too) and `libplacebo.so*` respectively.

> We have plenty of time to try each route, and if a full Metal port does not succeed (either it's not finished or not performant enough) before the 10.10 feature freeze, we could still use libplacebo without hwmap as a backup plan.

I agree. Using `hwupload/download` is always the *safest* option for VT hwctx.

**Comment by gnattu** [comment]
An initial Metal port is ready and showing good performance so far:

OpenCL:

```
frame=10490 fps= 74 q=-0.0 Lsize=  413202kB time=00:02:57.17 bitrate=19104.7kbits/s speed=1.26x
```

Metal:

```
frame=10493 fps=207 q=-0.0 Lsize=  416321kB time=00:02:58.08 bitrate=19151.5kbits/s dup=3 drop=0 speed=3.51x
```

The GPU power consumption is also significantly reduced (~3W to ~1W) as measured by `powermetrics`, and now the fps is bottlenecked mainly by the hardware decoder/encoders.

**Comment by nyanmisaka** [comment]
The perf uplift of the native impl looks promising. Apple’s OCL compat-layer is indeed a crap.

Any chance of testing it on x86-64? If it's stable enough we could even bring it to 10.9.
