### ISSUE TITLE
No audio in some streams

### ISSUE THREAD

**Issue by podhorsky-ksj** [jellyfin/jellyfin-ffmpeg#380]
**Describe The Bug**
I'm not sure, if it is related to here, but I can't think jellyfin itself could cause this

**Steps To Reproduce**

1. Select en audio, it is working
2. Select cz/sk audio, they are not working

**Expected Behavior**

I would like make cz audio working

**System (please complete the following information):**

- **Platform:** Linux
- **Operating System:** Archlinux
- **Virtualization**: no
- **Jellyfin Version:** 10.7.7
- **Jellyfin-FFmpeg Version:** 10.8.13
- **Hardware Acceleration:** VAAPI
- **CPU & GPU Model**: 
4x Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz

**MediaInfo**

**FFmpeg Logs**

[Log-cz.txt](https://github.com/jellyfin/jellyfin-ffmpeg/files/15054627/Log-cz.txt) - logs from video play with cz audio (no sound)
[Log-en.txt](https://github.com/jellyfin/jellyfin-ffmpeg/files/15054628/Log-en.txt) - logs form video play with en audio

**Additional Context**

**Comment by gnattu** [comment]
You are not even using jellyfin-ffmpeg

**Comment by podhorsky-ksj** [comment]
I tried ffmpeg-jellyfin  and it is the same. Even ffmpeg with every libraries. (user archlinux as ffmpeg-full).
I agree this is not in ffmpeg-jellyfin.  I have compared the ffmpeg commands, which was created by jellyfin and they are same for cz and en audio. I have to play with parameters, if it will make it work or not.
