### ISSUE TITLE
av1 (via dav1d) support

### ISSUE THREAD

**Issue by cromefire** [jellyfin/jellyfin-ffmpeg#39]
Add support for dav1d (and maybe libaom if it's needed), a av1 decoder ([build guide](https://xtechbiz.com/ffmpeg-dav1d-static-build-ubuntu-19-04/)).

This should enables ffmpeg to handle av1 transcoding correctly.

This seems to require ffmpeg 4.3 or 4.2 not sure, so it might have to be tested.

**Comment by cromefire** [comment]
To try dav1d in firefox (desktop), turn on "always prefer" [here](https://www.youtube.com/account_playback) and then try [this](https://www.youtube.com/watch?v=oAbB4dQOz4I&list=PLyqf6gJt7KuHBmeVzZteZUlNUQAVLwrZS) (ensure av1 is used in the stats for nerds)

Even 4K plays very smooth in firefox.

**Comment by RazeLighter777** [comment]
I implemented this in #43 but just wanted to note that dav1d performance is bad on 10-bit AV1 files. According to their documentation, 10 bit does not have as much assembly code written for it and thus is unable to optimize for 10 bit as fully.
