### ISSUE TITLE
my system is linux-musl x86_64

### ISSUE THREAD

**Issue by Yumega** [jellyfin/jellyfin-ffmpeg#398]
dose it mean jellyfin-ffmpeg doesn't support linux-musl x86_64 ?

**Comment by gnattu** [comment]
Not officially. This has been discussed before: https://github.com/jellyfin/jellyfin-ffmpeg/issues/361

It is not an easy task to ensure hardware acceleration will work properly with musl, and some of them will probably never work (like nvidia ones).

**Comment by gnattu** [comment]
As a workaround, you can run jellyfin inside docker which can give you a glibc environment.

**Comment by Yumega** [comment]
> As a workaround, you can run jellyfin inside docker which can give you a glibc environment.

it runs inside docker, but I want to install ffmpeg, how to intall

**Comment by gnattu** [comment]
> > As a workaround, you can run jellyfin inside docker which can give you a glibc environment.
> 
> it runs inside docker, but I want to install ffmpeg, how to intall

If you run Jellyfin inside docker it should comes with jellyfin-ffmpeg and you don't need to install it.

**Comment by Yumega** [comment]
> > > As a workaround, you can run jellyfin inside docker which can give you a glibc environment.
> > 
> > 
> > it runs inside docker, but I want to install ffmpeg, how to intall
> 
> If you run Jellyfin inside docker it should comes with jellyfin-ffmpeg and you don't need to install it.

the image is: lscr.io/linuxserver/jellyfin:latest,  jellyfin works, but what the path of jellyfin-ffmpeg is?  

there is nothing inside /usr/lib/jellyfin-ffmpeg/ffmpeg, I installed tdarr , it need ffmpeg to work
