### ISSUE TITLE
LibXv missing

### ISSUE THREAD

**Issue by BobOkisama** [jellyfin/jellyfin-ffmpeg#4]
Just installed the latest of this, compiled, make, and make install. Pointed JF 10.3.2 transcode to the /opt/jellyfin-ffmpeg path, it sees it and tries to use it. Queue up a 4k video forcing a transcode and it just sits there. Logs show:

/opt/jellyfin-ffmpeg/ffmpeg -i file:"movie.mp4" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 libx264 -pix_fmt yuv420p -preset slow -crf 21 -maxrate 3616000 -bufsize 7232000 -profile:v high -level 4.1 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -force_key_frames "expr:gte(t,n_forced*3)" -vf "scale=trunc(min(max(iw\,ih*dar)\,1280)/2)*2:trunc(ow/dar/2)*2" -copyts -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 384000 -af "volume=2" -f segment -max_delay 5000000 -avoid_negative_ts disabled -start_at_zero -segment_time 3  -individual_header_trailer 0 -segment_format mpegts -segment_list_type m3u8 -segment_start_number 0 -segment_list "/tmp/transcoding-temp/7a167fda6a22eec35538c53d4b783808.m3u8" -y "/tmp/transcoding-temp/7a167fda6a22eec35538c53d4b783808%d.ts"

/opt/jellyfin-ffmpeg/ffmpeg: error while loading shared libraries: libXv.so.1: cannot open shared object file: No such file or directory

**Comment by joshuaboniface** [comment]
How exactly did you build it?

**Comment by BobOkisama** [comment]
Did a git clone, configure, make, make install.
The same issue exists in the static build as well.

**Comment by joshuaboniface** [comment]
This repo can't be built like that, it's not going to follow the Debian rules - this one is designed to build within Docker/`dpkg-buildpackage` for multiple releases of both Debian and Ubuntu. To build your own from scratch I'd recommend using a stock ffmpeg source archive and manually specifying the `--configure` flags (from `debian/rules`).

**Comment by BobOkisama** [comment]
Well, I went ahead and deleted that, and then did a new git clone then ./build bionic amd64
I think it errored out... i think..

`
+ mv /jellyfin-ffmpeg_4.0.4-2-bionic_amd64.deb /jellyfin-ffmpeg_4.0.4-2_amd64.buildinfo /jellyfin-ffmpeg_4.0.4-2_amd64.changes /dist/deb/
+ chown -R root /tmp/tmp.dna9WSO1RN
+ mkdir ../bin
+ mmv '/tmp/tmp.dna9WSO1RN/deb/*.deb' ../bin/#1.deb
./build: line 98: mmv: command not found
+ cleanup
+ make -f Dockerfile.make clean
rm -f Dockerfile
+ rm -rf /tmp/tmp.dna9WSO1RN
`

**Comment by joshuaboniface** [comment]
Oh you'll need the command `mmv` (`apt install mmv`) - if you haven't heard of that command before, it's very useful!

**Comment by BobOkisama** [comment]
Installed that and then tried again and it finishes like:
`make[1]: Entering directory '/ffmpeg'
dh_gencontrol -- -v"4.0.4-2-bionic"
make[1]: Leaving directory '/ffmpeg'
   dh_md5sums
   dh_builddeb
dpkg-deb: building package 'jellyfin-ffmpeg' in '../jellyfin-ffmpeg_4.0.4-2-bionic_amd64.deb'.
 dpkg-genbuildinfo --build=binary
 dpkg-genchanges --build=binary >../jellyfin-ffmpeg_4.0.4-2_amd64.changes
dpkg-genchanges: info: binary-only upload (no source code included)
 dpkg-source --after-build ffmpeg
dpkg-buildpackage: info: binary-only upload (no source included)
+ popd
+ mkdir -p /dist/deb
/
+ mv /jellyfin-ffmpeg_4.0.4-2-bionic_amd64.deb /jellyfin-ffmpeg_4.0.4-2_amd64.buildinfo /jellyfin-ffmpeg_4.0.4-2_amd64.changes /dist/deb/
+ chown -R root /tmp/tmp.rWfgENoSe4
+ mkdir ../bin
+ true
+ mmv '/tmp/tmp.rWfgENoSe4/deb/*.deb' ../bin/#1.deb
+ mmv '/tmp/tmp.rWfgENoSe4/deb/*_amd64.*' ../bin/#1-bionic_amd64.#2
+ cleanup
+ make -f Dockerfile.make clean
rm -f Dockerfile
+ rm -rf /tmp/tmp.rWfgENoSe4
`

I don't see any files to install, or a docker built.

**Comment by joshuaboniface** [comment]
The files end up a directory above the repository, under `bin/`.

**Comment by joshuaboniface** [comment]
I trust you found the files @BobOkisama, I'm going to close this one out, but let me know if anything still doesn't work!
