### ISSUE TITLE
intel QSV didn't work with vetical video hevc

### ISSUE THREAD

**Issue by dieseld2** [jellyfin/jellyfin-ffmpeg#40]
Hi!
I found problem with playing vertical video from iphone 4k hevc. It's didn't play. Horizontal video from same phone, same codec etc plays well.

When I'm copy ffmpeg code to cmd, I get this error:

```
Impossible to convert between the formats supported by the filter 'graph 0 input from stream 0:0' and the filter 'auto_scaler_0'
Error reinitializing filters!
Failed to inject frame into filter network: Function not implemented
Error while processing the decoded data for stream #0:0
[libmp3lame @ 000001cfd9921f00] 4 frames left in the queue on closing
```

Windows, jellyfin_10.5.5 , HW encoding fully on, Intel HD 630 with latest driver.

I upload 2 video here, one is working, second is crashing
https://cloud.mail.ru/public/3pVV/5gaf2qjTK

**Comment by dieseld2** [comment]
same error with same files in docker with vaapi /dev/dri/renderD128
How can I fix this? Should I attach more info?

**Comment by Mylloon** [comment]
Still an issue in 2021

**Comment by Shadowghost** [comment]
Seems to work fine on 10.8 and ffmpeg 5.0.1

It gets rotatet while transcoding but that's a Jellyfin problem.
