### ISSUE TITLE
x11grab disabled in Linux portable builds

### ISSUE THREAD

**Issue by bjia56** [jellyfin/jellyfin-ffmpeg#420]
I'm interested in using Jellyfin FFmpeg to do X11 screen capture on Linux. Testing with release 6.0.1-7, the x11grab demuxer device does not show up when running `ffmpeg -devices`. I found it was disabled here: https://github.com/jellyfin/jellyfin-ffmpeg/blob/3924a882403bdc56b83c064c5ee12f0c18402d59/builder/variants/defaults-gpl.sh#L8

Just wanted to see if there was a reason X11 was disabled? I'm able to get a portable build with x11grab by commenting out that line.

**Comment by nyanmisaka** [comment]
The main reason is that our pre-builds are targeting headless servers. Therefore, X11 is avoided as much as possible in the build parameters. For example, vaapi may require a monitor when built with X11.

So I recommend you to customize it in your own repository.

**Comment by bjia56** [comment]
Got it, that makes sense. Thanks for the explanation.
