### ISSUE TITLE
Opportunity for a new default tonemap mode

### ISSUE THREAD

**Issue by gnattu** [jellyfin/jellyfin-ffmpeg#429]
Jellyfin currently has two tonemap modes: MAX mode, which applies TMO to the maximum of the RGB channels, and RGB mode, which applies TMO to each RGB channel individually. However, both methods have significant shortcomings in certain cases. A new mode that applies TMO on the relative luminance has recently been merged in #418 and #416. This mode resolves the distorted color/overly saturated color issue in RGB mode and the significant hue shift issue on bright pixels in MAX mode. 

My current working draft introduces a new mode called ITP mode. This mode does not operate in the linear RGB color space like the other methods but operates in the ICtCp color space. The TMO is applied to the Intensity of the ICtCp color. This mode also has a special desaturation method that preserves hue in ICtCp space, which should be closer to human perception due to the design of this color space. This tonemap mode preserves colors in bright pixels even better than the LUM mode, and I propose to make this mode the new default for Jellyfin 10.10 and jellyfin-ffmpeg 7.0. 

The major drawback of this mode is the extra computation required for the color space conversion. However, for BT.2390 methods, this is not much slower because this color space does not need the extra non-linearity applied to the signal like other modes, as such non-linearity functions are already applied during color space conversion. For other TMOs that expect a linear signal, extra linearization and de-linearization are required, which makes this mode slower. For users with lower spec GPUs, I suggest them to use the LUM mode which is a good enough alternative for common cases.

To demonstrate the effectiveness of this tonemap mode, I made some sample scene images as examples.

Let's begin with the customizable desaturation parameter. Look at the following furnace example with `desat=0.5`:

**RGB mode:**
![desat_rgb](https://github.com/user-attachments/assets/98ded936-8e3e-4551-ad0f-bacadbfdc174)

**MAX mode:**
![desat_max](https://github.com/user-attachments/assets/f85b05d8-8473-4d90-96f3-cc8558d752d9)

**LUM mode:**
![desat_lum](https://github.com/user-attachments/assets/fd4edfcd-25d4-4581-b481-e873117cbf3a)

**ITP mode:**
![desat_itp](https://github.com/user-attachments/assets/b62f324a-3bff-4f5a-892b-9035b426217e)

As we can see from this example, ICtCp-based desaturation shows a significant advantage over RGB-based desaturation. LUM and MAX modes have a significant hue shift, causing the furnace to appear too red. The RGB mode does not experience as severe a hue shift, but the desaturation is not effective as the color remains overly saturated. ITP mode preserves the hue while gradually turning the overly bright furnace color to white, producing most naturally looking color.

In fact, for this scene, the ICtCp-based tone mapping does not have over saturation problem in the first place, I made this sample mostly to show the hue preserving capability of ICtCp. This is the results of `desat=0`:

**RGB mode:**
![origin_rgb](https://github.com/user-attachments/assets/1e9e7c39-2045-4ad5-a132-f80a580e6390)

**MAX mode:**
![origin_max](https://github.com/user-attachments/assets/f72fc27e-c6f5-40b5-906e-6825d243bc9b)

**LUM mode:**
![origin_lum](https://github.com/user-attachments/assets/b9b5aee8-9f72-4f5f-a9ae-18dbe653aca6)

**ITP mode:**
![origin_itp](https://github.com/user-attachments/assets/1414c8f9-add3-47a9-972d-46c5d06a4fd8)

As you can see, the ITP mode produces natural-looking colors and does not require extra desaturation.

-----

To demonstrate the detail-preserving capability for bright pixels, let look at this glass blowing scene:

**RGB mode:**
![rgb](https://github.com/user-attachments/assets/b6069e61-b383-4a27-b523-8a72f8e11bcd)

**MAX mode:**
![max](https://github.com/user-attachments/assets/56c83aed-2650-4f9a-b264-e1158baeec8c)

**LUM mode:**
![lum](https://github.com/user-attachments/assets/02876864-3388-4fda-8091-15751776bacc)

**ITP mode:**
![itp](https://github.com/user-attachments/assets/aedd5f39-e7d4-474b-9d15-91de8346f7c2)

As you can see, RGB mode preserves highlights but produces unnatural colors. MAX mode loses most of the highlights, and while LUM mode preserves highlights better than MAX, it is still not as effective as ITP mode.

Another example is the campfire scene:

**RGB mode:**
![rgb](https://github.com/user-attachments/assets/96cf63b3-878f-4d9f-9c8b-9bda3704745f)

**MAX mode:**
![max](https://github.com/user-attachments/assets/08b81d4d-86e2-428e-9719-bc661199c935)

**LUM mode:**
![lum](https://github.com/user-attachments/assets/a32efdc1-6ce7-485e-ae77-d0c4fd0ce961)

**ITP mode:**
![itp](https://github.com/user-attachments/assets/44437c18-385a-4765-b9c0-e47949125519)

Pay attention to the details of the flame in the bottom right corner.

-------

To further demonstrate the limitation of current modes (MAX and RGB), lets look at this scene that direct captures the sun:

**RGB mode:**
![rgb](https://github.com/user-attachments/assets/82f2c50c-9974-4a5c-98a6-103a355c0e2d)

**MAX mode:**
![max](https://github.com/user-attachments/assets/0f695d8e-eece-402f-a900-58165f7c66b8)

**LUM mode:**
![lum](https://github.com/user-attachments/assets/a0514620-e2c4-4a2c-bd24-8aeff38363e9)

**ITP mode:**
![itp](https://github.com/user-attachments/assets/3f86c338-4ecb-4755-8144-46b64807c728)

As you can see, both of the current modes render sunlight poorly. Both LUM and ITP modes improve the sunlight significantly. In this case, LUM mode has a darker sun border, which appears less "natural" but is not subjectively bad.

Direct capture of the sun is an extreme case, but the current modes have more limitations. Let's look at this bridge scene shot at night:

**RGB mode:**
![rgb](https://github.com/user-attachments/assets/f3938744-ae73-4cfd-8c9c-fa26c98c5704)

**MAX mode:**
![max](https://github.com/user-attachments/assets/7c5aca84-ffa8-40ca-b9d2-e900bd9a710c)

**LUM mode:**
![lum](https://github.com/user-attachments/assets/41a9e3b3-1489-47da-86af-f2fe798ea537)

**ITP mode:**
![itp](https://github.com/user-attachments/assets/79251120-3bb0-40e9-8ff4-babee7cad4a0)

RGB mode is too dark for a night scene, and MAX mode renders the lights on the road way too red. Both LUM and ITP modes produce much more natural colors in this case. For this scene, the LUM and ITP results are not visually distinguishable.

For more scene comparisons, I have made a zip file that includes additional scenes not shown here:[tonemode_comparison_extra.zip](https://github.com/user-attachments/files/16516217/tonemode_comparison_extra.zip)

If there is no objection I will make the ITP mode as the default tonemap mode for jellyfin-ffmpeg7 and Jellyfin 10.10.

**Comment by nyanmisaka** [comment]
No objection to enabling new method/mode by default if it provides a better look and feel, and falls back to using LUM instead on weak GPUs. But your RGB mode seems off to me.

![2 mp4_20240807_174626 185](https://github.com/user-attachments/assets/6dc7347a-191b-4077-85bc-90804dfc2688)
![2 mp4_20240807_174738 354](https://github.com/user-attachments/assets/d6a6dff7-e896-4e76-913e-08b3e5019a45)
![2 mp4_20240807_180853 246](https://github.com/user-attachments/assets/2064d3db-0c59-461d-9ed1-d47fa82a72ca)
![3 mp4_20240807_181438 237](https://github.com/user-attachments/assets/9a8b0cbd-6da7-419a-abd7-f773d4515c9d)
![3 mp4_20240807_181601 144](https://github.com/user-attachments/assets/7d5eb617-adb6-48a6-8efe-6707449c9afd)

**Comment by gnattu** [comment]
> No objection to enabling new method/mode by default if it provides a better look and feel, and falls back to using LUM instead on weak GPUs. But your RGB mode seems off to me.
> 

Yep, the original one divided too deep factor and yours are correct, and RGB mode is problematic when desired to retain bright saturated colors as the hue shift is also sever at those colors.:

RGB:

![rgb](https://github.com/user-attachments/assets/b699ab4c-11fc-433a-a2f8-8b43fa14b20a)

ITP:

![itp](https://github.com/user-attachments/assets/9874c51d-06fb-4fa7-9ed1-9e9fcc1fb611)

**Comment by nyanmisaka** [comment]
BTW my suggestion in #416 may be wrong, because primaries have been converted from bt2020 to bt709 in `lrgb2lrgb()` when doing hdr2sdr. The luminance coeffs should be determined by the setting of the `:p=bt2020/bt709` option if we want to do tone-mapping in the target primaries instead of the source primaries.

**Comment by gnattu** [comment]
> because primaries have been converted from bt2020 to bt709 in lrgb2lrgb() when doing hdr2sdr

That's why I modified the shaders further. In my latest draft ITP and LUM mode will now map in source space and perform lrgb to lrgb after tone mapping(partially addressed https://github.com/nyanmisaka/jellyfin-ffmpeg/pull/5)

The current draft has Metal, OpenCL and CUDA modified for this change, but the actual PR is blocked by the ffmpeg7 PR as the patches are based on that.

**Comment by nyanmisaka** [comment]
> > because primaries have been converted from bt2020 to bt709 in lrgb2lrgb() when doing hdr2sdr
> 
> That's why I modified the shaders further. In my latest draft ITP and LUM mode will now map in source space and perform lrgb to lrgb after tone mapping(partially addressed [nyanmisaka#5](https://github.com/nyanmisaka/jellyfin-ffmpeg/pull/5))
> 
> The current draft has Metal, OpenCL and CUDA modified for this change, but the actual PR is blocked by the ffmpeg7 PR as the patches are based on that.

The vulkan changes are more problematic than I expected. Let's merge this PR into the jellyfin-7.0 branch so you can continue working on it.
