### ISSUE TITLE
Could you please compile a Mac version with the shared library?

### ISSUE THREAD

**Issue by chbtime** [jellyfin/jellyfin-ffmpeg#442]
Could you please compile a Mac version with shared library? Currently there are only static executables, I would like to have avcodec.dylib, avformat.dylib, etc.
Thanks

**Comment by gnattu** [comment]
We don't change our CI to build for targets that we are not using, and I'm not sure if it will have linker issue with the shared build using current config. You can try modify https://github.com/jellyfin/jellyfin-ffmpeg/blob/jellyfin/builder/variants/mac64-gpl.sh and https://github.com/jellyfin/jellyfin-ffmpeg/blob/jellyfin/builder/variants/macarm64-gpl.sh to change `defaults-gpl.sh` to `defaults-gpl-shared.sh`, and then follow https://github.com/jellyfin/jellyfin-ffmpeg/blob/jellyfin/builder/Buildmac.md to build your self
