### ISSUE TITLE
Transcoding video orientation

### ISSUE THREAD

**Issue by Aviatorpaal** [jellyfin/jellyfin-ffmpeg#455]
**Describe The Bug**

Playing videos recorded with vertical orientation or "upside down" orientation transcodes to incorrectly flipped videos. Disabling transcoding (direct play) stops this behavior in Jellyfin.

**Steps To Reproduce**

1. Enable Intel QSV hardware acceleration
2. Play Apple iPhone video file shot with different orientation than "straight" in Jellyfin (HEVC "camera app" or H264 Snapchat content)
3. Select lower resolution for the video to start transcoding

**Expected Behavior**

Video should respect the orientation metadata from the mp4 or mov file

**System (please complete the following information):**

- **Platform:** [e.g. Linux, Windows]
Linux 6.6.44
- **Operating System:** [e.g. Ubuntu 20.04, Debian 11, Windows 10]
Debian 12 on Truenas Scale 24.10
- **Virtualization**: [e.g. Docker, KVM, LXC]
Docker
- **Jellyfin Version:** [e.g. 10.7.7]
10.9.10
- **Jellyfin-FFmpeg Version:** [e.g. 4.4.1-2]
6.0.1-8-bookworm amd64
- **Hardware Acceleration:** [e.g. QSV, Nvidia, VAAPI, AMD AMF]
QSV
- **CPU & GPU Model**: [e.g. i7-1165G7, UHD 630, GTX 1650, VEGA 64]
N100, Intel UHD 750 MHz
**MediaInfo**

iPhone 11 and iPhone 15 Pro video footage, both SDR and HDR 1080p and 4K content
`mov,mp4,m4a,3gp,3g2,mj2","Size":125618682,"Name":"23-08-20 16-50-40 2018`
**FFmpeg Logs**

`{"Protocol":0,"Id":"2c2b27b5950c2a873982b7b330004c6e","Path":"/media/pa-iphonevideo/23-08-20 16-50-40 2018.mov","EncoderPath":null,"EncoderProtocol":null,"Type":0,"Container":"mov,mp4,m4a,3gp,3g2,mj2","Size":125618682,"Name":"23-08-20 16-50-40 2018","IsRemote":false,"ETag":"3b07c97d718654e47631e73fc12b2304","RunTimeTicks":207800000,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"OpenToken":null,"RequiresClosing":false,"LiveStreamId":null,"BufferMs":null,"RequiresLooping":false,"SupportsProbing":true,"VideoType":0,"IsoType":null,"Video3DFormat":null,"MediaStreams":[{"Codec":"hevc","CodecTag":"hvc1","Language":"und","ColorRange":null,"ColorSpace":"bt709","ColorTransfer":"bt709","ColorPrimaries":"bt709","DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/600","CodecTimeBase":null,"Title":null,"VideoRange":1,"VideoRangeType":1,"VideoDoViTitle":null,"AudioSpatialFormat":0,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"LocalizedHearingImpaired":null,"DisplayTitle":"4K HEVC SDR","NalLengthSize":null,"IsInterlaced":false,"IsAVC":false,"ChannelLayout":null,"BitRate":48079198,"BitDepth":8,"RefFrames":1,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":true,"IsForced":false,"IsHearingImpaired":false,"Height":2160,"Width":3840,"AverageFrameRate":59.961502,"RealFrameRate":59.94006,"Profile":"Main","Type":1,"AspectRatio":"16:9","Index":0,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":"yuv420p","Level":153,"IsAnamorphic":false},{"Codec":"aac","CodecTag":"mp4a","Language":"und","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/44100","CodecTimeBase":null,"Title":"Core Media Audio","VideoRange":0,"VideoRangeType":0,"VideoDoViTitle":null,"AudioSpatialFormat":0,"LocalizedUndefined":null,"LocalizedDefault":"Default","LocalizedForced":null,"LocalizedExternal":"External","LocalizedHearingImpaired":null,"DisplayTitle":"Core Media Audio - AAC - Stereo - Default","NalLengthSize":null,"IsInterlaced":false,"IsAVC":false,"ChannelLayout":"stereo","BitRate":189237,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":2,"SampleRate":44100,"IsDefault":true,"IsForced":false,"IsHearingImpaired":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":"LC","Type":0,"AspectRatio":null,"Index":1,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":null,"CodecTag":"mebx","Language":"und","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/600","CodecTimeBase":null,"Title":null,"VideoRange":0,"VideoRangeType":0,"VideoDoViTitle":null,"AudioSpatialFormat":0,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"LocalizedHearingImpaired":null,"DisplayTitle":null,"NalLengthSize":null,"IsInterlaced":false,"IsAVC":false,"ChannelLayout":null,"BitRate":3,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":true,"IsForced":false,"IsHearingImpaired":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":4,"AspectRatio":null,"Index":2,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":null,"CodecTag":"mebx","Language":"und","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/600","CodecTimeBase":null,"Title":null,"VideoRange":0,"VideoRangeType":0,"VideoDoViTitle":null,"AudioSpatialFormat":0,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"LocalizedHearingImpaired":null,"DisplayTitle":null,"NalLengthSize":null,"IsInterlaced":false,"IsAVC":false,"ChannelLayout":null,"BitRate":3,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":true,"IsForced":false,"IsHearingImpaired":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":4,"AspectRatio":null,"Index":3,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":null,"CodecTag":"mebx","Language":"und","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/600","CodecTimeBase":null,"Title":null,"VideoRange":0,"VideoRangeType":0,"VideoDoViTitle":null,"AudioSpatialFormat":0,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"LocalizedHearingImpaired":null,"DisplayTitle":null,"NalLengthSize":null,"IsInterlaced":false,"IsAVC":false,"ChannelLayout":null,"BitRate":69075,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":true,"IsForced":false,"IsHearingImpaired":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":4,"AspectRatio":null,"Index":4,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null}],"MediaAttachments":[],"Formats":[],"Bitrate":48361379,"Timestamp":null,"RequiredHttpHeaders":{},"TranscodingUrl":null,"TranscodingSubProtocol":0,"TranscodingContainer":null,"AnalyzeDurationMs":null,"DefaultAudioStreamIndex":null,"DefaultSubtitleStreamIndex":null}

/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -probesize 1G -init_hw_device vaapi=va:,kernel_driver=i915,driver=iHD -init_hw_device qsv=qs@va -filter_hw_device qs -hwaccel vaapi -hwaccel_output_format vaapi -noautorotate -i file:"/media/pa-iphonevideo/23-08-20 16-50-40 2018.mov" -noautoscale -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_qsv -low_power 1 -preset veryfast -look_ahead 0 -b:v 9810763 -maxrate 9810763 -bufsize 19621526 -g:v:0 180 -keyint_min:v:0 180 -vf "setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_vaapi=w=1920:h=1080:format=nv12:extra_hw_frames=24,hwmap=derive_device=qsv,format=qsv" -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type fmp4 -hls_fmp4_init_filename "1e7947e02d63f9bca1ae0eb69df17e39-1.mp4" -start_number 0 -hls_segment_filename "/cache/transcodes/1e7947e02d63f9bca1ae0eb69df17e39%d.mp4" -hls_playlist_type vod -hls_list_size 0 -y "/cache/transcodes/1e7947e02d63f9bca1ae0eb69df17e39.m3u8"

ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
libva info: VA-API version 1.22.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_22
libva info: va_openDriver() returns 0
libva info: VA-API version 1.22.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_22
libva info: va_openDriver() returns 0
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'file:/media/pa-iphonevideo/23-08-20 16-50-40 2018.mov':
  Metadata:
    major_brand     : qt  
    minor_version   : 0
    compatible_brands: qt  
    creation_time   : 2023-08-20T14:50:40.000000Z
    com.apple.quicktime.location.accuracy.horizontal: 35.000000
    com.apple.quicktime.location.ISO6709: +69.6628+018.9259+086.264/
    com.apple.quicktime.make: Apple
    com.apple.quicktime.model: iPhone 11
    com.apple.quicktime.software: 16.6
    com.apple.quicktime.creationdate: 2023-08-20T16:50:40+0200
  Duration: 00:00:20.78, start: 0.000000, bitrate: 48361 kb/s
  Stream #0:0[0x1](und): Video: hevc (Main) (hvc1 / 0x31637668), yuv420p(tv, bt709), 3840x2160, 48079 kb/s, 59.96 fps, 59.94 tbr, 600 tbn (default)
    Metadata:
      creation_time   : 2023-08-20T14:50:40.000000Z
      handler_name    : Core Media Video
      vendor_id       : [0][0][0][0]
      encoder         : HEVC
    Side data:
      displaymatrix: rotation of -180.00 degrees
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 189 kb/s (default)
    Metadata:
      creation_time   : 2023-08-20T14:50:40.000000Z
      handler_name    : Core Media Audio
      vendor_id       : [0][0][0][0]
  Stream #0:2[0x3](und): Data: none (mebx / 0x7862656D), 0 kb/s (default)
    Metadata:
      creation_time   : 2023-08-20T14:50:40.000000Z
      handler_name    : Core Media Metadata
  Stream #0:3[0x4](und): Data: none (mebx / 0x7862656D), 0 kb/s (default)
    Metadata:
      creation_time   : 2023-08-20T14:50:40.000000Z
      handler_name    : Core Media Metadata
  Stream #0:4[0x5](und): Data: none (mebx / 0x7862656D), 69 kb/s (default)
    Metadata:
      creation_time   : 2023-08-20T14:50:40.000000Z
      handler_name    : Core Media Metadata
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> h264 (h264_qsv))
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
libva info: VA-API version 1.22.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_22
libva info: va_openDriver() returns 0
libva info: VA-API version 1.22.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_22
libva info: va_openDriver() returns 0
[hls @ 0x55f471304b80] Opening '/cache/transcodes/1e7947e02d63f9bca1ae0eb69df17e39-1.mp4' for writing
Output #0, hls, to '/cache/transcodes/1e7947e02d63f9bca1ae0eb69df17e39.m3u8':
  Metadata:
    encoder         : Lavf60.3.100
  Stream #0:0: Video: h264, qsv(tv, bt709, progressive), 1920x1080, q=2-31, 9810 kb/s, 59.94 fps, 60k tbn (default)
    Metadata:
      encoder         : Lavc60.3.100 h264_qsv
    Side data:
      cpb: bitrate max/min/avg: 9810763/0/9810763 buffer size: 19621526 vbv_delay: N/A
      displaymatrix: rotation of -180.00 degrees
  Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 189 kb/s (default)
frame=    0 fps=0.0 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
frame=   63 fps=0.0 q=24.0 size=N/A time=00:00:01.13 bitrate=N/A speed=2.11x    
frame=  137 fps=132 q=24.0 size=N/A time=00:00:02.36 bitrate=N/A speed=2.28x    
[hls @ 0x55f471304b80] Opening '/cache/transcodes/1e7947e02d63f9bca1ae0eb69df17e390.mp4' for writing
frame=  210 fps=136 q=22.0 size=N/A time=00:00:03.59 bitrate=N/A speed=2.33x    
frame=  286 fps=140 q=23.0 size=N/A time=00:00:04.85 bitrate=N/A speed=2.37x    
frame=  361 fps=141 q=22.0 size=N/A time=00:00:06.10 bitrate=N/A speed=2.39x    
[hls @ 0x55f471304b80] Opening '/cache/transcodes/1e7947e02d63f9bca1ae0eb69df17e391.mp4' for writing
frame=  434 fps=142 q=23.0 size=N/A time=00:00:07.33 bitrate=N/A speed= 2.4x    
frame=  508 fps=143 q=23.0 size=N/A time=00:00:08.56 bitrate=N/A speed=2.41x    
[hls @ 0x55f471304b80] Opening '/cache/transcodes/1e7947e02d63f9bca1ae0eb69df17e392.mp4' for writing
frame=  582 fps=143 q=24.0 size=N/A time=00:00:09.79 bitrate=N/A speed=2.41x    
frame=  656 fps=144 q=24.0 size=N/A time=00:00:11.02 bitrate=N/A speed=2.42x    
[hls @ 0x55f471304b80] Opening '/cache/transcodes/1e7947e02d63f9bca1ae0eb69df17e393.mp4' for writing
frame=  731 fps=144 q=25.0 size=N/A time=00:00:12.26 bitrate=N/A speed=2.42x    
frame=  805 fps=145 q=23.0 size=N/A time=00:00:13.49 bitrate=N/A speed=2.42x    
frame=  879 fps=145 q=23.0 size=N/A time=00:00:14.74 bitrate=N/A speed=2.43x    
[hls @ 0x55f471304b80] Opening '/cache/transcodes/1e7947e02d63f9bca1ae0eb69df17e394.mp4' for writing
frame=  952 fps=145 q=23.0 size=N/A time=00:00:15.97 bitrate=N/A speed=2.43x    
frame= 1026 fps=145 q=22.0 size=N/A time=00:00:17.20 bitrate=N/A speed=2.43x    
[hls @ 0x55f471304b80] Opening '/cache/transcodes/1e7947e02d63f9bca1ae0eb69df17e395.mp4' for writing
frame= 1101 fps=145 q=23.0 size=N/A time=00:00:18.43 bitrate=N/A speed=2.43x    
frame= 1175 fps=145 q=22.0 size=N/A time=00:00:19.69 bitrate=N/A speed=2.43x    
[hls @ 0x55f471304b80] Opening '/cache/transcodes/1e7947e02d63f9bca1ae0eb69df17e396.mp4' for writing
frame= 1246 fps=146 q=24.0 Lsize=N/A time=00:00:19.71 bitrate=N/A speed=2.31x    
video:25328kB audio:481kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown`

This video was transcoded upside down

**Comment by gnattu** [comment]
Fixed in upcoming 10.10 https://github.com/jellyfin/jellyfin/pull/11250
