### ISSUE TITLE
Not all release assets built for 4.2.1-7?

### ISSUE THREAD

**Issue by TwizzyDizzy** [jellyfin/jellyfin-ffmpeg#49]
Hi folks,

for release `4.2.1-7` there have been explicit releases for Debian Buster (`jellyfin-ffmpeg_4.2.1-7-buster_amd64.deb
`). Seems like those [haven't been built](https://github.com/jellyfin/jellyfin-ffmpeg/releases) for `4.3.1-1`.

Is this a broken build/release pipeline or is there a valid reason for that?

Cheers & Thanks
Thomas

**Comment by nyanmisaka** [comment]
Just ignore those wrong packages. Only the tagged source code will be release there.
Deb packages have been moved to our repository. Same for jellyfin and jellyfin-web binaries.
Release post: https://github.com/jellyfin/jellyfin/releases/tag/v10.6.0

https://repo.jellyfin.org/releases/server/ubuntu/versions/jellyfin-ffmpeg/
https://repo.jellyfin.org/releases/server/debian/versions/jellyfin-ffmpeg/

You can also add our repository to your apt so as to install jellyfin-ffmpeg by `sudo apt install jellyfin-ffmpeg -y`.

**Comment by TwizzyDizzy** [comment]
Alright, thanks for the fast feedback :)

Cheers
Thomas
