### ISSUE TITLE
Compile ERROR: vulkan requested but not found, from version 7.0

### ISSUE THREAD

**Issue by clion007** [jellyfin/jellyfin-ffmpeg#494]
**Describe The Bug**

When I compile 7.0.*-* on alpine linux, I get ERROR: vulkan requested but not found. But I am sure installed vulkan-loader-dev aready.
**Steps To Reproduce**

1. Enable '--enable-vulkan'
2. Play file '....'
3. Check logs '....'

**Expected Behavior**

**System (please complete the following information):**

- **Platform:** [e.g. Linux, Windows]
- **Operating System:Alpine 3. 20[e.g. Ubuntu 20.04, Debian 11, Windows 10]
- **Virtualization**: KVM[e.g. Docker, KVM, LXC]
- **Jellyfin Version:10.10.0 [e.g. 10.7.7]
- **Jellyfin-FFmpeg Version:7.0.2-1 -- 7.0.2-4 [e.g. 4.4.1-2]
- **Hardware Acceleration:** [e.g. QSV, Nvidia, VAAPI, AMD AMF]
- **CPU & GPU Model**: [e.g. i7-1165G7, UHD 630, GTX 1650, VEGA 64]

**MediaInfo**

**FFmpeg Logs**

**Additional Context**

**Comment by gnattu** [comment]
We don't provide direct support for musl based systems due to the compatibility issues with hardware acceleration APIs. But we do have a community supported alpine package.

See https://github.com/jellyfin/jellyfin-ffmpeg/issues/361
and https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/62512

**Comment by clion007** [comment]
It work fine on the version of 6.0.1-8, Alpine linux also has gcc lib, not only musl based. The error only compile version from 7.0.

**Comment by nyanmisaka** [comment]
> It work fine on the version of 6.0.1-8, Alpine linux also has gcc lib, not only musl based. The error only compile version from 7.0.

https://ffmpeg.org/download.html#releases

You can try to build vanilla FFmpeg 7.0.2 from upstream I think you will get the same error. We didn't touch any Vulkan related options in `configure` so we are not to blame for this.

**Comment by clion007** [comment]
> > It work fine on the version of 6.0.1-8, Alpine linux also has gcc lib, not only musl based. The error only compile version from 7.0.
> 
> https://ffmpeg.org/download.html#releases
> 
> You can try to build vanilla FFmpeg 7.0.2 from upstream I think you will get the same error. We didn't touch any Vulkan related options in `configure` so we are not to blame for this.

So, it's bug of upstream? I got it. Thanks!

**Comment by nyanmisaka** [comment]
> > > It work fine on the version of 6.0.1-8, Alpine linux also has gcc lib, not only musl based. The error only compile version from 7.0.
> > 
> > 
> > https://ffmpeg.org/download.html#releases
> > You can try to build vanilla FFmpeg 7.0.2 from upstream I think you will get the same error. We didn't touch any Vulkan related options in `configure` so we are not to blame for this.
> 
> So, it's bug of upstream? I got it. Thanks!

Not necessarily, but it has something to do with alpine and your build environment. Because we did not encounter this problem in the Linux and Windows versions built with GCC.

**Comment by FintasticMan** [comment]
@clion007 the issue here is that the vulkan version on Alpine 3.20 is outdated. Switching to the edge repositories should fix your issue.
