### ISSUE TITLE
ffmpeg error

### ISSUE THREAD

**Issue by DestroMedia** [jellyfin/jellyfin-ffmpeg#507]
**Describe The Bug**
Forgive me if i dont lay this out right
Issue with ffmpeg via Immich, was directed here to talk with someone more knowledgable about ffmpeg behaviour
ffmpeg fails to encode video

**Steps To Reproduce**

On immich ive been trying to re transcode my entire library it gets through a bunch of videos and then eventually produces an error which ill post 
it doesnt always error out on the same video though which was odd to me and if i manually re encode a video that it errors out on it encodes fine.

**Expected Behavior**
work lol

**System (please complete the following information):**

- **Platform:** Linux
- **Operating System:** Ubuntu 24.10
- **Virtualization**: Docker
- **Jellyfin Version:** im not sure i assume the latest but its what ever immich uses ?
- **Jellyfin-FFmpeg Version:** im not sure i assume the latest but its what ever immich uses ?
- **Hardware Acceleration:** QSV
- **CPU & GPU Model**: 12900KS and ARC A770

**MediaInfo**

**FFmpeg Logs**

**Additional Context**
[Nest] 7  - 11/21/2024, 4:28:19 PM     LOG [Microservices:MediaService] Encoding video edd8e1be-f663-4ae3-9ec0-bdfb13b2b29b with QSV acceleration
[Nest] 7  - 11/21/2024, 4:28:19 PM   DEBUG [Microservices:MediaRepository] ffmpeg -n 10 /usr/bin/ffmpeg -hwaccel qsv -hwaccel_output_format qsv -async_depth 4 -noautorotate -threads 1 -qsv_device /dev/dri/card2 -i upload/library/redacted/2023/April/IMG_9353.mp4 -y -c:v hevc_qsv -c:a aac -movflags faststart -fps_mode passthrough -map 0:0 -map 0:1 -bf 7 -refs 5 -g 256 -tag:v hvc1 -v verbose -vf scale_qsv=720:-1:async_depth=4:mode=hq:format=nv12 -preset 1 -global_quality:v 23 -maxrate 3000k -bufsize 6000k upload/encoded-video/d58953e2-6cb8-45b6-9e60-a7bea1259423/ed/d8/edd8e1be-f663-4ae3-9ec0-bdfb13b2b29b.mp4
[Nest] 7  - 11/21/2024, 4:28:20 PM   DEBUG [Microservices:MediaRepository] Transcoding 30.34% done for output edd8e1be-f663-4ae3-9ec0-bdfb13b2b29b.mp4
[Nest] 7  - 11/21/2024, 4:28:20 PM   DEBUG [Microservices:MediaRepository] Transcoding 71.84% done for output edd8e1be-f663-4ae3-9ec0-bdfb13b2b29b.mp4
[Nest] 7  - 11/21/2024, 4:28:20 PM   DEBUG [Microservices:MediaRepository] Transcoding 100.00% done for output edd8e1be-f663-4ae3-9ec0-bdfb13b2b29b.mp4
[Nest] 7  - 11/21/2024, 4:28:20 PM     LOG [Microservices:MediaService] Successfully encoded edd8e1be-f663-4ae3-9ec0-bdfb13b2b29b

[Nest] 7  - 11/21/2024, 4:28:22 PM     LOG [Microservices:MediaService] Encoding video 4acd4263-fba6-4608-aea9-73255a54943a with QSV acceleration
[Nest] 7  - 11/21/2024, 4:28:22 PM   DEBUG [Microservices:MediaRepository] ffmpeg -n 10 /usr/bin/ffmpeg -hwaccel qsv -hwaccel_output_format qsv -async_depth 4 -noautorotate -threads 1 -qsv_device /dev/dri/card2 -i upload/library/redacted/2021/October/IMG_9370.mov -y -c:v hevc_qsv -c:a aac -movflags faststart -fps_mode passthrough -map 0:0 -map 0:1 -bf 7 -refs 5 -g 256 -tag:v hvc1 -v verbose -vf scale_qsv=720:-1:async_depth=4:mode=hq,hwmap=derive_device=opencl,tonemap_opencl=desat=0:format=nv12:matrix=bt709:primaries=bt709:transfer=bt709:range=pc:tonemap=hable:tonemap_mode=lum:peak=100,hwmap=derive_device=qsv:reverse=1,format=qsv -preset 1 -global_quality:v 23 -maxrate 3000k -bufsize 6000k upload/encoded-video/d58953e2-6cb8-45b6-9e60-a7bea1259423/4a/cd/4acd4263-fba6-4608-aea9-73255a54943a.mp4
[Nest] 7  - 11/21/2024, 4:28:22 PM   ERROR [Microservices:MediaRepository]   libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
[AVHWDeviceContext @ 0x5e73c160300] libva: VA-API version 1.22.0
[AVHWDeviceContext @ 0x5e73c160300] libva: vaGetDriverNames() failed with operation failed
[AVHWDeviceContext @ 0x5e73c160300] libva: User requested driver 'iHD'
[AVHWDeviceContext @ 0x5e73c160300] libva: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
[AVHWDeviceContext @ 0x5e73c160300] libva: Found init function __vaDriverInit_1_22
[AVHWDeviceContext @ 0x5e73c160300] libva: va_openDriver() returns 0
[AVHWDeviceContext @ 0x5e73c160300] Initialised VAAPI connection: version 1.22
[AVHWDeviceContext @ 0x5e73c160300] VAAPI driver: Intel iHD driver for Intel(R) Gen Graphics - 24.4.2 (b6b411f).
[AVHWDeviceContext @ 0x5e73c160300] Driver not found in known nonstandard list, using standard behaviour.
[AVHWDeviceContext @ 0x5e73c160240] Use Intel(R) oneVPL to create MFX session, API version is 2.13, the required implementation version is 1.3
libva info: VA-API version 1.22.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_22
libva info: va_openDriver() returns 0
libva info: VA-API version 1.22.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_22
libva info: va_openDriver() returns 0
libva info: VA-API version 1.22.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_22
libva info: va_openDriver() returns 0
libva info: VA-API version 1.22.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_22
libva info: va_openDriver() returns 0
[AVHWDeviceContext @ 0x5e73c160240] Initialize MFX session: implementation version is 2.13
Selecting decoder 'hevc_qsv' because of requested hwaccel method qsv
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'upload/library/redacted/2021/October/IMG_9370.mov':
  Metadata:
    major_brand     : qt  
    minor_version   : 0
    compatible_brands: qt  
    creation_time   : 2021-10-24T10:45:12.000000Z
    com.apple.quicktime.location.accuracy.horizontal: 5.936149
    com.apple.quicktime.location.ISO6709: -33.8912+150.8619+075.383/
    com.apple.quicktime.make: Apple
    com.apple.quicktime.model: iPhone 13 Pro Max
    com.apple.quicktime.software: 15.1
    com.apple.quicktime.creationdate: 2021-10-23T21:55:54+1100
  Duration: 00:00:09.42, start: 0.000000, bitrate: 97071 kb/s
  Stream #0:0[0x1](und): Video: hevc (Main 10), 1 reference frame (hvc1 / 0x31637668), yuv420p10le(tv, bt2020nc/bt2020/arib-std-b67, left), 3840x2160, 93681 kb/s, 58.62 fps, 59.94 tbr, 600 tbn (default)
      Metadata:
        creation_time   : 2021-10-24T10:45:12.000000Z
        handler_name    : Core Media Video
        vendor_id       : [0][0][0][0]
        encoder         : HEVC
      Side data:
        DOVI configuration record: version: 1.0, profile: 8, level: 10, rpu flag: 1, el flag: 0, bl flag: 1, compatibility id: 4
        displaymatrix: rotation of -90.00 degrees
        Ambient Viewing Environment, ambient_illuminance=314.000000, ambient_light_x=0.312700, ambient_light_y=0.329000
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 210 kb/s (default)
      Metadata:
        creation_time   : 2021-10-24T10:45:12.000000Z
        handler_name    : Core Media Audio
        vendor_id       : [0][0][0][0]
  Stream #0:2[0x3](und): Data: none (mebx / 0x7862656D), 0 kb/s (default)
      Metadata:
        creation_time   : 2021-10-24T10:45:12.000000Z
        handler_name    : Core Media Metadata
  Stream #0:3[0x4](und): Data: none (mebx / 0x7862656D), 0 kb/s (default)
      Metadata:
        creation_time   : 2021-10-24T10:45:12.000000Z
        handler_name    : Core Media Metadata
[out#0/mp4 @ 0x5e73c163c00] Adding streams from explicit maps...
[vost#0:0/hevc_qsv @ 0x5e73c1eb280] Created video stream from input stream 0:0
[aost#0:1/aac @ 0x5e73c1e9a80] Created audio stream from input stream 0:1
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (hevc_qsv) -> hevc (hevc_qsv))
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))
[vost#0:0/hevc_qsv @ 0x5e73c1eb280] Starting thread...
[aost#0:1/aac @ 0x5e73c1e9a80] Starting thread...
[vf#0:0 @ 0x5e73c1f1940] Starting thread...
[af#0:1 @ 0x5e73c1f1cc0] Starting thread...
[vist#0:0/hevc @ 0x5e73c183900] [dec:hevc_qsv @ 0x5e73c069640] Starting thread...
[aist#0:1/aac @ 0x5e73c183a80] [dec:aac @ 0x5e73c183f00] Starting thread...
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0x5e73c12c980] Starting thread...
Press [q] to stop, [?] for help
[graph_1_in_0:1 @ 0x5e744050300] tb:1/44100 samplefmt:fltp samplerate:44100 chlayout:stereo
[AVHWDeviceContext @ 0x5e746020480] VAAPI driver: Intel iHD driver for Intel(R) Gen Graphics - 24.4.2 (b6b411f).
[AVHWDeviceContext @ 0x5e746020480] Driver not found in known nonstandard list, using standard behaviour.
[hevc_qsv @ 0x5e73c214400] Decoder: output is video memory surface
[hevc_qsv @ 0x5e73c214400] Use Intel(R) oneVPL to create MFX session with the specified MFX loader
[AVHWDeviceContext @ 0x5e7460209c0] VAAPI driver: Intel iHD driver for Intel(R) Gen Graphics - 24.4.2 (b6b411f).
[AVHWDeviceContext @ 0x5e7460209c0] Driver not found in known nonstandard list, using standard behaviour.
[hevc_qsv @ 0x5e73c214400] Decoder: output is video memory surface
[hevc_qsv @ 0x5e73c214400] Use Intel(R) oneVPL to create MFX session with the specified MFX loader
[graph 0 input from stream 0:0 @ 0x5e742060840] w:3840 h:2160 pixfmt:qsv tb:1/600 fr:60000/1001 sar:0/1 csp:bt2020nc range:tv
[AVHWDeviceContext @ 0x5e742060c00] VAAPI driver: Intel iHD driver for Intel(R) Gen Graphics - 24.4.2 (b6b411f).
[AVHWDeviceContext @ 0x5e742060c00] Driver not found in known nonstandard list, using standard behaviour.
[Parsed_scale_qsv_0 @ 0x5e742060480] Use Intel(R) oneVPL to create MFX session with the specified MFX loader
[Parsed_scale_qsv_0 @ 0x5e742060480] VPP: input is video memory surface
[Parsed_scale_qsv_0 @ 0x5e742060480] VPP: output is video memory surface
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 18446744073709551603) > this->size() (which is 86)

[Nest] 7  - 11/21/2024, 4:28:22 PM   ERROR [Microservices:MediaService] Error occurred during transcoding: ffmpeg was killed with signal SIGABRT
[Nest] 7  - 11/21/2024, 4:28:22 PM   ERROR [Microservices:MediaService] Retrying with QSV acceleration disabled
[Nest] 7  - 11/21/2024, 4:28:22 PM   DEBUG [Microservices:MediaRepository] ffmpeg -n 10 /usr/bin/ffmpeg -i upload/library/redacted/2021/October/IMG_9370.mov -y -c:v hevc -c:a aac -movflags faststart -fps_mode passthrough -map 0:0 -map 0:1 -tag:v hvc1 -v verbose -vf scale=720:-2,tonemapx=tonemap=hable:desat=0:p=bt709:t=bt709:m=bt709:r=pc:peak=100:format=yuv420p -preset veryslow -b:v 2069k -minrate 1034.5k -maxrate 3000k -pass 1 -passlogfile upload/encoded-video/d58953e2-6cb8-45b6-9e60-a7bea1259423/4a/cd/4acd4263-fba6-4608-aea9-73255a54943a.mp4 -f null /dev/null
[Nest] 7  - 11/21/2024, 4:28:23 PM   DEBUG [Microservices:MediaRepository] Transcoding 5.19% done, estimated 4m, 34s remaining for output null

**Comment by DestroMedia** [comment]
i notice too when i try do the work on the igpu it hits the render engine ? it shouldnt be doing that right ?

**Comment by gnattu** [comment]
Your GPU driver crashed maybe due to heavy load. Sorry I can't help you with that.

**Comment by mertalev** [comment]
From some more investigation, it turns out that this is a ProRes source video. Hardware decoding without tone-mapping (just setting `format=nv12`) does seem to work based on their testing, but it fails when using tone-mapping. I think this is most likely because `scale_qsv` doesn't have an output format set in the command, so it tries to use the original format.

**Comment by mertalev** [comment]
For posterity, the file actually wasn't ProRes, just HDR. This makes sense since ProRes can't be hardware-decoded with Quick Sync. The fix for this case was to not use card2 and instead use renderD129. For some reason, card2 worked on most videos, but not on certain videos or in certain situations. renderD129 worked consistently. I have no idea why this would be the case, but I assume it's something at the driver level as gnattu mentioned.

**Comment by nyanmisaka** [comment]
Using card* with vaapi/qsv is not a common practice in both ffmpeg docs and source code, which is much more picky due to some historical reasons and the fact that it’s mostly used by mode-setting instead of rendering/computing. Not sure why do you use that.

**Comment by mertalev** [comment]
Interesting! The code prefers card* over renderD* since card* is needed for NVIDIA cards IIRC. Maybe it should only prefer card* for NVIDIA and use renderD* for VAAPI / QSV?

**Comment by nyanmisaka** [comment]
NVIDIA's proprietary driver is an outlier and taints the kernel. It uses more than just card*, and has many custom interfaces. There's no way to set card* for NVIDIA in ffmpeg, just card index number starting from 0.

**Comment by mertalev** [comment]
Yes, I misremembered and it doesn't actually set card* for NVIDIA. Actually for QSV, we don't set the device by default (only for VAAPI) and just use FFmpeg's heuristics, but OP set it to card2 explicitly because it apparently used the iGPU instead of the dGPU. So I guess the solution would just be to always prefer renderD* over card* and set it explicitly.

**Comment by nyanmisaka** [comment]
Then there is no need for OP to pass multiple GPUs to docker.
