### ISSUE TITLE
jellyfin-ffmpeg for centos 7

### ISSUE THREAD

**Issue by Ho2x** [jellyfin/jellyfin-ffmpeg#51]
No RPM jellyfin-ffmpeg for centos 7 ?
Thank's

**Comment by joshuaboniface** [comment]
At this time we do no provide an RPM-based `jellyfin-ffmpeg`. Someone would need to contribute this as well as a standard build procedure similar to the Debian package.

**Comment by Shadowghost** [comment]
Duplicate of #5
