### ISSUE TITLE
Unmet libx264 dependency when building jellyfin docker based on bullseye

### ISSUE THREAD

**Issue by bzzbrr** [jellyfin/jellyfin-ffmpeg#52]
**Describe the bug**
Attempting to build jellyfin docker based on Debian Bullseye fails due to unmet libx264 dependency.  Presumably this is because libx264-159 is not a bullseye package (anymore?).  [libx264-160 is available in bullseye (version 2:0.160.3011+gitcde9a93-2)](https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=libx264).

I assume this is the correct repository for this issue out of the jellyfin repos.  I understand bullseye might not be supported, but it works in every other respect.  Apologies for any mistakes as this is my first reporting.

**System (please complete the following information):**
 - OS: Ubuntu 20.04 amd64
 - Jellyfin Version: stable

**To Reproduce**
1. Git clone jellyfin-metapackages
2. Update Dockerfile references from buster to bullseye
3. Build container
```
user@host:/path/build$ cd jellyfin-metapackages/
user@host:/path/build/jellyfin-metapackages$ diff Dockerfile.amd64.original Dockerfile.amd64.bullseye
6c6
< FROM debian:buster-slim
---
> FROM debian:bullseye-slim
26c26
<  && echo 'deb [arch=amd64] https://repo.jellyfin.org/debian buster main' > /etc/apt/sources.list.d/jellyfin.list \
---
>  && echo 'deb [arch=amd64] https://repo.jellyfin.org/debian bullseye main' > /etc/apt/sources.list.d/jellyfin.list \

user@host:/path/build/jellyfin-metapackages$ docker build -f Dockerfile.amd64.bullseye -t bulltest/jellyfin .
```

**Logs**
```
deb [arch=amd64] https://repo.jellyfin.org/debian bullseye main
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease
Get:3 https://repo.jellyfin.org/debian bullseye InRelease [6639 B]
Hit:4 http://deb.debian.org/debian bullseye-updates InRelease
Get:5 https://sgp1.mirror.jellyfin.org/debian bullseye/main amd64 Packages [1694 B]
Fetched 8333 B in 12s (695 B/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
openssl is already the newest version (1.1.1g-1).
openssl set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 jellyfin-ffmpeg : Depends: libx264-159 (>= 2:0.159.2999+git296494a) but it is not installable
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c apt-get update  && apt-get install --no-install-recommends --no-install-suggests -y ca-certificates gnupg wget apt-transport-https  && wget -O - https://repo.jellyfin.org/jellyfin_team.gpg.key | apt-key add -  && echo 'deb [arch=amd64] https://repo.jellyfin.org/debian bullseye main' > /etc/apt/sources.list.d/jellyfin.list  && cat /etc/apt/sources.list.d/jellyfin.list  && apt-get update  && apt-get install --no-install-recommends --no-install-suggests -y mesa-va-drivers jellyfin-ffmpeg openssl locales libfontconfig1 libfreetype6  && apt-get remove gnupg wget apt-transport-https -y  && apt-get clean autoclean -y  && apt-get autoremove -y  && rm -rf /var/lib/apt/lists/*  && mkdir -p ${JELLYFIN_MEDIA_DIR} ${JELLYFIN_DATA_DIR} ${JELLYFIN_CACHE_DIR}  && chmod 777 ${JELLYFIN_MEDIA_DIR} ${JELLYFIN_DATA_DIR} ${JELLYFIN_CACHE_DIR}  && sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && locale-gen' returned a non-zero code: 100
user@host:/path/build/jellyfin-metapackages$
```

**Comment by rbviz** [comment]
Same on unstable. When you have libx264-160 on your repo it is instantly incompatible.

Try installing missing package (worked for me):
http://ftp.br.debian.org/debian/pool/main/x/x264/libx264-159_0.159.2999+git296494a-2+b1_amd64.deb

**Comment by mjog** [comment]
Same for bullseye on arm64 (ie. not x86) - except I can't even find an old version of the deb as a workaround :(

**Comment by nyanmisaka** [comment]
@mjog 
I build with the lastest depends.
`sudo apt install ./jellyfin-ffmpeg_4.3.1-2-bullseye_arm64.deb`
[jellyfin-ffmpeg_4.3.1-2-bullseye_arm64.zip](https://github.com/jellyfin/jellyfin-ffmpeg/files/5540472/jellyfin-ffmpeg_4.3.1-2-bullseye_arm64.zip)

**Comment by bzzbrr** [comment]
I can confirm that jellyfin successfully builds on bullseye thanks to #53.  Closing.
`
Get:48 http://deb.debian.org/debian bullseye/main amd64 libx264-160 amd64 2:0.160.3011+gitcde9a93-2+b2 [539 kB]`
