### ISSUE TITLE
JF can't seem to handle multiple M3U tuner/EPG setups

### ISSUE THREAD

**Issue by eqpaisley** [jellyfin/jellyfin-ffmpeg#58]
Adding a 2nd EPG to the interface un-maps the 1st M3U-EPG setup and Map Channels seems to ignore what tuner a given EPG is supposed to support. 

**Steps Taken**
- Add M3U No 1 
- Add XML EPG No 1  
- everything works, channels often map automatically
- Add M3U No 2
- Add XML EPG No 2 
- Mapping of M3U No 1  is gone OR M3U No 2 will not ever map.
- Attempts to manually re-map do not work 
- JF seems to only be able load a single XML EPG

It also appears that JF doesn't purge deleted channel lineups. For example, I loaded PlutoTV (M3U and EPG) but free PBS Stations (M3U and EPG).   I later deleted the PlutoTV M3u and EPG.  However, when I attempt to MAP CHANNELS for the PBS Stations, I am ONLY presented with the Pluto channels. This is despite the fact that the Pluto EPG was added ONLY for use with the Pluto M3u tuner and the PBS M3U is assigned to a specific PBS M3u.

Ubuntu 18.04.5   JF  10.64

**Comment by m0ngr31** [comment]
Probably linked to this: https://github.com/jellyfin/jellyfin/issues/6103

**Comment by crobibero** [comment]
If this is still an issue please reopen the issue in the proper repository.
