### ISSUE TITLE
NVEnc transcoding fails if input or output video resolution is greater than 4k

### ISSUE THREAD

**Issue by esmorun** [jellyfin/jellyfin-ffmpeg#60]
If the source video resolution is greater than 4096 and NVEnc hardware decoding and encoding is activated, the transcode will fail no matter what. Disabling hardware decoding will let me hardware encode the video but only if I change the output resolution to something lower than 4k (Jellyfin attempts to do a 5k --> 5k, unless I manually change to a lower quality setting in the web UI). Software only transcoding 5k --> 5k works fine.

I can do 5k --> 5k  full hardware transcodes with another software (Rigaya Nvenc), so it seems theres an artificial limitation in ffmpeg?

[FFmpeg-log.txt](https://github.com/jellyfin/jellyfin-ffmpeg/files/5899839/FFmpeg-log.txt)

[h264_cuvid @ 0000025dbe600040] Video width 5120 not within range from 48 to 4096
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (h264_cuvid) -> h264 (h264_nvenc))
  Stream #0:1 -> #0:1 (copy)
Error while opening decoder for input stream #0:0 : Invalid argument

**Comment by nyanmisaka** [comment]
`[h264_cuvid @ 0000025dbe600040] Video width 5120 not within range from 48 to 4096`

Cuvid decoder said that your card is not capable of decoding 5k resolution videos. Is that a Pascal based GPU?
https://github.com/FFmpeg/FFmpeg/blob/6de039823c2ffcf88e8bfff0d4e3ed9d5601a122/libavcodec/cuviddec.c#L787

If it's a Pascal or newer GPU, try this PR with Jellyfin 10.7.
https://github.com/jellyfin/jellyfin/pull/5107

**Comment by esmorun** [comment]
Thanks. It's a Turing based GPU but I realise that it only supports higher resolutions for HEVC: https://en.wikipedia.org/wiki/Nvidia_NVENC

Ideally, in this case Jellyfin should have fallen back to software decoding and lowered the output resolution to whatever is the maximum supported by the hardware encoder, but I guess that's a completely different topic :).

I'm on 10.7.0rc3 though and have enabled the "Allow encoding in HEVC format" setting in Jellyfin, so maybe it should have done "ffmpeg.exe -c:v hevc_nvenc ..." instead? Or is the option just for software transcoding? (Tested on Android Mobile and MS Edge browser).

**Comment by nyanmisaka** [comment]
HEVC support in currently only available on Apple and WebOS.

Android client can support HEVC but it's still sending H264 profiles to server, additional changes is needed in [ExoPlayerPlugin.js](https://github.com/jellyfin/jellyfin-android/blob/a02ca6ceae2384d96f44930ff482ec1849cc21bf/app/src/main/assets/native/ExoPlayerPlugin.js#L358).

As for MS Edge, `hls.js` in web client doesn't support HEVC via HLS. We are working on Vue client to use shaka-player, which support HEVC via FMP4-HLS. Try this commit in jellyfin-vue, it should support HEVC in Edge.
https://github.com/nyanmisaka/jellyfin-vue/commit/be2acc6df006c3e7995e3db410cae4e9db90f692

**Comment by nyanmisaka** [comment]
Software fallback is still not supported, we need to make a new ffmpeg wrapper and hardware caps detector to achieve this.

**Comment by Shadowghost** [comment]
Since this doesn't seem to be an issue with ffmpeg I'll close it.
