### ISSUE TITLE
jellyfin-ffmpeg (4.3.1-4) broke QSV transcoding

### ISSUE THREAD

**Issue by FunDeckHermit** [jellyfin/jellyfin-ffmpeg#62]
OS: Ubuntu 20.04

[relevant Reddit post](https://www.reddit.com/r/jellyfin/comments/ljoozp/intel_quicksyncqsv_transcoding_broke_with/)

When checking the logs: `Error during encoding: device failed (-17)`

Not sure if this issue should be here or the general Jellyfin repo.

**Comment by fightforlife** [comment]
Same here on J3455.

    image: linuxserver/jellyfin:10.6.4-1-ls95 <-working fine
    image: linuxserver/jellyfin:10.6.4-1-ls96 <- error as below


I know it is not the official docker image but the only changes are:
ca-certificates20201027ubuntu0.20.04.1 to ca-certificates20210119~20.04.1
**jellyfin-ffmpeg4.3.1-3-focal to jellyfin-ffmpeg4.3.1-4-focal**
libldap-2.4-22.4.49+dfsg-2ubuntu1.5 to libldap-2.4-22.4.49+dfsg-2ubuntu1.6
libldap-common2.4.49+dfsg-2ubuntu1.5 to libldap-common2.4.49+dfsg-2ubuntu1.6


```
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (hevc_qsv) -> h264 (h264_qsv))
  Stream #0:1 -> #0:1 (aac (native) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help
Output #0, hls, to '/config/data/transcodes/286304083d50f88764ac6e8a54d5dba1.m3u8':
  Metadata:
    encoder         : Lavf58.45.100
    Stream #0:0: Video: h264 (h264_qsv), qsv, 1920x1080 [SAR 1:1 DAR 16:9], q=-1--1, 8003 kb/s, 25 fps, 90k tbn, 25 tbc (default)
    Metadata:
      encoder         : Lavc58.91.100 h264_qsv
    Side data:
      cpb: bitrate max/min/avg: 8003532/0/8003532 buffer size: 16007064 vbv_delay: N/A
    Stream #0:1: Audio: mp3 (libmp3lame), 48000 Hz, stereo, fltp, 224 kb/s (default)
    Metadata:
      encoder         : Lavc58.91.100 libmp3lame
[h264_qsv @ 0x559e6f5a2640] Error during encoding: device failed (-17)
Video encoding failed
[libmp3lame @ 0x559e6f7e47c0] 3 frames left in the queue on closing
Conversion failed!
```

**Comment by fightforlife** [comment]
This has to be related to this change: https://github.com/jellyfin/jellyfin-ffmpeg/pull/59

**Comment by fightforlife** [comment]
linuxserver is still using the old ffmpeg since this change: https://github.com/linuxserver/docker-jellyfin/commit/ede49b23395ac766f811e1466a452ea04579e1e1#diff-41567ece253e75278bc44ff9e68adc494e505e96f75c4f9cc692579f82d1dc46

discussion here: https://github.com/jellyfin/jellyfin/issues/5993

**Comment by Shadowghost** [comment]
Can anyone please check again with `4.4.1-2`?

**Comment by Shadowghost** [comment]
Reopen if it's still a problem.
