### ISSUE TITLE
jellyfin-ffmpeg 4.3.2-1-focal qsv transcoding fails with Intel Media Driver 21.3.1

### ISSUE THREAD

**Issue by caiusseverus** [jellyfin/jellyfin-ffmpeg#74]
Intel have updated the non-free iHD driver again and it has broken compatibility with the current jellyfin-ffmpeg version.
Reverting to 21.2.2 fixes the issue pending an update to ffmpeg.

**Comment by nyanmisaka** [comment]
jf-ffmpeg 4.3.2 requires iHD 21.2.x
jf-ffmpeg 4.4 requires iHD 21.3.x

Do not update intel driver frequently unless it will fix certain bugs on your graphics.

**Comment by sbranden** [comment]
Will the releases be updated to include jf-ffmpeg 4.4?
I see only jf-ffmpeg-4.3.2.1 being latest here?
https://repo.jellyfin.org/releases/server/ubuntu/versions/jellyfin-ffmpeg/

**Comment by Shadowghost** [comment]
`jellyfin-ffmpeg` now ships the driver directly to guarantee compatibility.
