### ISSUE TITLE
[RPi] [Bullseye] Package requires rebuild for breaking libraspberrypi0 change

### ISSUE THREAD

**Issue by MichaIng** [jellyfin/jellyfin-ffmpeg#75]
The libraspberrypi0 got a breaking change with its last release on Bullseye, with shared library objects now having `.0` suffixes. The Jellyfin FFmpeg now fails to find the old library names and hence requires a rebuild against current libraspberrypi0/-dev.

On Buster this change has not been rolled out and likely won't happen.

**Comment by sensharma** [comment]
Any updates on this? If this repo is not being maintained actively, should we switch to standard ffmpeg instead? Thanks.
