### ISSUE TITLE
How to Install---for a Beginner

### ISSUE THREAD

**Issue by AdiAbuAli** [jellyfin/jellyfin-ffmpeg#78]
Hi,
Am not expert in coding, but just need this repository to be installed as depnedency for other application.

should the below enough for installation:
**apt install git-all
git clone https://github.com/jellyfin/jellyfin-ffmpeg.git
./configure
make**

**Comment by nyanmisaka** [comment]
apt install git mmv make docker.io
systemctl start docker
git clone https://github.com/jellyfin/jellyfin-ffmpeg.git
cd jellyfin-ffmpeg
mkdir target
./build [distro] [arch] target

You can get the latest build from https://repo.jellyfin.org/releases/server/ubuntu/versions/jellyfin-ffmpeg/4.3.2-1/

**Comment by curtwagner1984** [comment]
@nyanmisaka  What about windows installation?

**Comment by nyanmisaka** [comment]
replace the last line above with `./build-win64`

**Comment by curtwagner1984** [comment]
Thank you for the reply!  I didn't see it earlier.
