### ISSUE TITLE
how to update ffmpeg 5？

### ISSUE THREAD

**Issue by stevenliuit** [jellyfin/jellyfin-ffmpeg#83]
how to update ffmpeg 5？

**Comment by nyanmisaka** [comment]
We have no urgent reason to update to FFmpeg 5.0 as it won't bring any performance improvements for our use case.

**Comment by raver2046** [comment]
Ffmpeg 5 support dolby vision .
Fair enough?

**Comment by nyanmisaka** [comment]
It indeed supports parsing DV metadata but the important feature tone-mapping is not supported.

**Comment by LoaneShark** [comment]
Allegedly 5.0 does add tone-mapping and remuxing of Dolby Vision files, v4.4 was the one that added metadata parsing.
