### ISSUE TITLE
Limit resolution on older graphics cards?

### ISSUE THREAD

**Issue by NoeelMoeskops** [jellyfin/jellyfin-ffmpeg#86]
Hi,

I am not sure wherever to create this issue on Jellyfin or jellyfin-mpeg. But my best guess is to start here.
In my server I have an i3-2120 with integrated graphics. I have configured Jellyfin to use the iGPU for transcoding. And its is working correctly for video's in full-HD, however my iGPU is not capable of scaling video higher than 2048x2048. ffmpeg outputs:
```
[hevc @ 0x5636a426adc0] No support for codec hevc profile 2.
[hevc @ 0x5636a426adc0] Failed setup for format vaapi_vld: hwaccel initialisation returned error.
[Parsed_scale_vaapi_2 @ 0x5636a46a2d00] Hardware does not support scaling to size 3840x2160 (constraints: width 0-2048 height 0-2048).
[Parsed_scale_vaapi_2 @ 0x5636a46a2d00] Failed to configure output pad on Parsed_scale_vaapi_2
Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #0:0
```
This error is however not noticed in Jellyfin as it will just say that ffmpeg returned with exit code 1. And the streaming stops.
Is it possible to limit the scaling to the supported resolution of the graphics card. So that is does not crash, but instead limit the resolution. Or that on failure it will switch back to software transcoding?

**Comment by Shadowghost** [comment]
You can't use HEVC with your iGPU.
The one in your  i3-2120 [does only support AVC](https://en.wikipedia.org/wiki/Intel_Quick_Sync_Video#Hardware_decoding_and_encoding).
