### ISSUE TITLE
Sorry for my confusion. How do I run this version of ffmpeg to utilize the GPUs of a Jetson Nano

### ISSUE THREAD

**Issue by jmorris644** [jellyfin/jellyfin-ffmpeg#87]
I have been able to compile and can run this version of ffmpeg. But I cannot get the CLI right.

I am trying to use a rtsp stream as input out to a .mp4 file. 

Either I get errors or nothing happens. Either way, jtop shows that NVENC, NVDEC, and NVJPG are all off.

Thanks

**Comment by nyanmisaka** [comment]
Jetson Nano uses a different video api called nvmpi. You should use jetson-ffmpeg instead. https://github.com/jocover/jetson-ffmpeg

**Comment by jmorris644** [comment]
Thanks. This is really old. We should close it. I am now using gstreamer and not ffmpeg.

**Comment by wisdom0623** [comment]
> gstreamer
Would you mind sharing how to use it for jetson nano under the official docker? I'm failing to deploy jetson-ffmpeg under docker

**Comment by wisdom0623** [comment]
老哥知道怎么在官方docker下面加速了吗？我死活加速不上

> 谢谢。这真的很老了。我们应该关闭它。我现在使用的是 gstreamer 而不是 ffmpeg。
