### ISSUE TITLE
Tonemapping is broken with intel-media-va-driver-non-free

### ISSUE THREAD

**Issue by coucoulala** [jellyfin/jellyfin-ffmpeg#88]
When taking the docker image `jellyfin/jellyfin:10.8.0-alpha5-amd64` as base image and adding intel-media-va-driver-non-free, QSV will start working but tone-mapping is broken for software, VA-API and QSV transcoding. Switching back to the unmodified docker image with free Intel drivers makes tonemapping work again.

**Comment by Shadowghost** [comment]
Try with upgrading `jellyfin-ffmpeg` inside of the image instead of installing the driver.

Our current ffmpeg build includes the driver and all required dependencies in the currently available upstream version.
