### ISSUE TITLE
Hardware decoding broken since 14.4.1-1 on GB-BACE-3150 / Intel N3150

### ISSUE THREAD

**Issue by u-cav** [jellyfin/jellyfin-ffmpeg#92]
I am using the image `nyanmisaka/jellyfin:latest` for testing. The same issue occurs with the linuxserver-jellyfin image.

By default, jellyfin-ffmpeg `4.4.1-1` is installed, and transcoding in Jellyfin fails with the following error:

```
jellyfin-test  | [14:33:03] [INF] [17] Jellyfin.Api.Helpers.TranscodingJobHelper: /usr/lib/jellyfin-ffmpeg/ffmpeg -init_hw_device vaapi=va:/dev/dri/renderD128 -filter_hw_device va -autorotate 0 -i file:"/data/file.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_vaapi -rc_mode VBR -b:v 336000 -maxrate 336000 -bufsize 672000 -profile:v:0 high -force_key_frames:0 "expr:gte(t,0+n_forced*3)" -vf "setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale=trunc(min(max(iw\,ih*dar)\,426)/2)*2:trunc(ow/dar/2)*2,format=nv12,hwupload_vaapi" -codec:a:0 aac -ac 2 -ab 384000 -af "volume=2" -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/config/transcodes/e368adf3e4fa183b2eb9de133fdac2b5%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/config/transcodes/e368adf3e4fa183b2eb9de133fdac2b5.m3u8"
jellyfin-test  | [14:33:03] [ERR] [20] Jellyfin.Api.Helpers.TranscodingJobHelper: FFmpeg exited with code 1
jellyfin-test  | [14:33:03] [ERR] [20] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL GET /videos/aaee5545-f5e5-22ac-515d-8e292635f6c1/hls1/main/0.ts.
jellyfin-test  | MediaBrowser.Common.FfmpegException: FFmpeg exited with code 1
jellyfin-test  |    at Jellyfin.Api.Helpers.TranscodingJobHelper.StartFfMpeg(StreamState state, String outputPath, String commandLineArguments, HttpRequest request, TranscodingJobType transcodingJobType, CancellationTokenSource cancellationTokenSource, String workingDirectory)
```

Transcoding works correctly if jellyfin-ffmpeg is downgraded to 4.3.2-1 with:
```
wget https://repo.jellyfin.org/releases/server/debian/versions/jellyfin-ffmpeg/4.3.2-1/jellyfin-ffmpeg_4.3.2-1-bullseye_amd64.deb
apt install ./jellyfin-ffmpeg_4.3.2-1-bullseye_amd64.deb
```

ffmpeg command output with more details (same command run inside the container): [ffmpeg.txt](https://github.com/jellyfin/jellyfin-ffmpeg/files/8123853/ffmpeg.txt)

lshw dump: [lshw.txt](https://github.com/jellyfin/jellyfin-ffmpeg/files/8123845/lshw.txt)

I am available for additional info and testing.
Thank you very much for the excellent work that you are doing on jellyfin.

**Comment by nyanmisaka** [comment]
Can you run the original command with ` -async_depth 1` added right after the `-c:v h264_vaapi` and see if it works?

**Comment by u-cav** [comment]
Thanks for the reply. Adding that parameter, I get the same result.

Original command and output: [log_jellyfin-ffmpeg_92_original.txt](https://github.com/jellyfin/jellyfin-ffmpeg/files/8133223/log_jellyfin-ffmpeg_92_original.txt)

Modified command and output:  [log_jellyfin-ffmpeg_92_modified.txt](https://github.com/jellyfin/jellyfin-ffmpeg/files/8133224/log_jellyfin-ffmpeg_92_modified.txt)

The only difference seems to be an additional error: `[h264_vaapi @ 0x559bbd2697c0] Output failed: -5.`
