### ISSUE TITLE
4.4.1-2 bug,Unable to use openCL tone mapping.

### ISSUE THREAD

**Issue by shaino** [jellyfin/jellyfin-ffmpeg#94]
After upgrading 4.4.1-2 in Docker(both nyanmisaka latest and linuxserver nightly), HDR movie transcoding failed.
There is no issue with choosing VPP tone mapping.
Select openCL tone map immediately appears issue.

The ffmpeg log shows that no transcoding has started:
-----------ffmpeg log -----------
.....
[matroska,webm @ 0x562722d39f80] sub2video: using 3840x2152 canvas
----------- The following blank space -------------

Downgrade to 4.4.1-1 to return to normal.

**Comment by nyanmisaka** [comment]
Is is still an issue after upgrading the OpenCL runtime to the 22.05 build?
https://github.com/intel/compute-runtime/releases/tag/22.05.22297

**Comment by shaino** [comment]
linuxserver nightly is based on Ubuntu 20.04,so I updated the latest intel driver 21.4.1 and the companion intel-opencl-icd:

vainfo: VA-API version: 1.13 (libva 2.13.0)                                     
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 21.4.1 (be9
2568)                           

I'm not sure if it installs runtime 22.05 automatically,I will manually install these runtime libs and try again.

**Comment by nyanmisaka** [comment]
You don't need to install the intel-media-driver anymore since the jellyfin-ffmpeg 4.4.1-2 comes with built-in media-driver.

**Comment by shaino** [comment]
Thx
The 4.4.1-2 runs smoothly after installing intel runtime 22.05.(both linuxserver nightly,nyanmisaka latest,QNAP/Synology)

**Comment by shaino** [comment]
Last time someone mentioned that the N5105 hardware acceleration cannot be used.
A simple test showed that the driver was incompatible.
Can intel 21.4.1 drivers or fmpeg4.4.1-2 with built-in media-drvier solve this issue?
Unfortunately my N5105 has already been returned.

**Comment by nyanmisaka** [comment]
For N5105 N6005 jasper lake chips, the `i915.enable_guc=2` kernel parameter must be added to enable hardware encoding.

**Comment by lxiongh** [comment]
> 
My qnap ts-264c (N5105) hardware acceleration cannot be used too (VAAPI mode)
how can I set parameter "i915.enable_guc=2" in jellyfin admin web ui.

**Comment by lxiongh** [comment]
> My qnap ts-264c (N5105) hardware acceleration cannot be used too (VAAPI mode)
> how can I set parameter "i915.enable_guc=2" in jellyfin admin web ui.

My qnap ts-264c (N5105) hardware acceleration cannot be used too (VAAPI mode)
how can I set parameter "i915.enable_guc=2" in jellyfin admin web ui.

**Comment by lxiongh** [comment]
> For N5105 N6005 jasper lake chips, the `i915.enable_guc=2` kernel parameter must be added to enable hardware encoding.

My qnap ts-264c (N5105) hardware acceleration cannot be used too (VAAPI mode).
CPU load is high to 100% when play 4k movie, and decode at about 10fps
how can I set parameter "i915.enable_guc=2" in jellyfin admin web ui.

**Comment by nyanmisaka** [comment]
https://jellyfin.org/docs/general/administration/hardware-acceleration.html#intel-gen9-and-gen11-igpus
